### ISSUE TITLE
writer buffer between songs

### ISSUE THREAD

**Issue by jwallet** [jwallet/spy-spotify#100]
**What problem will this new feature resolves ?**
that the song before the next one, don't get recorded on it.

**What feature or enhancement would you like to see added ?**
an instance of a buffer outside the recorder class, and apply it before starting to record to the current file and write to the buffer once a silence is detected or a new frequency instead of the current writer. once the recorder ends the instance is unmount, we create a new instance of a recorder and re-apply the buffer.

---
Want to back this issue? **[Post a bounty on it!](https://issuehunt.io/r/jwallet/spy-spotify/issues/100)** We accept bounties via [IssueHunt](https://issuehunt.io/r/jwallet/spy-spotify).

**Comment by Endres** [comment]
After all, I suppose it is a bug that sometimes the "cut" between two songs is not done precisely at all. Sometimes I have up to 10 seconds of the next song in the current recording, whereas these 10 seconds are missing at the beginning of the next song.

Currently I resolve that manually by analyzing the waveforms of multiple recordings of the same track, but after all it is quite annoying to having to do that by hand.

**Comment by jwallet** [comment]
I understand.
If Spotify does not change its title when the new track plays, then Spytify can't do much. Maybe that explains the 10 secs delay. If this happens again I will like to know if this was the cause. Just hover the Spotify icon in the taskbar to reveal to app preview with the App title above, like so:

![image](https://user-images.githubusercontent.com/23088305/76482595-f6109380-63ea-11ea-97f1-f3c980202878.png)
