### ISSUE TITLE
Logs & skip/don't record downloaded songs

### ISSUE THREAD

**Issue by chaoscreater** [jwallet/spy-spotify#101]
Sometimes, Spytify will crash and I won't know what the last downloaded song is. If I have a playlist of 500 songs, I may sometimes do a bit of comaprison to see what has been downloaded and what has not.

If we could get a log output after each song has been downloaded, sorted in the same as the "Title" column in Spotify, then that would be a lot easier to compare. Alternatively, if we can get an option to skip downloaded songs, that would be even better.

**Comment by jwallet** [comment]
i think the issue here is that Spytify crashes. any way to reproduce it

**Comment by chaoscreater** [comment]
No, I haven't been able to reproduce the issue and couldn't find anything in the event logs. Happens intermittently on 2 different Win10 machines. Happens on the latest build as well as older builds. I'd be happy to just do a quick restart and resume the recording. Just need a way to skip the downloaded music.

**Comment by jwallet** [comment]
if you record use a playlist and disable random selection, go from top to bottom. easier to resume if spytify crashes. i will consider adding a log file to appdata

**Comment by chaoscreater** [comment]
Yup, that's what I'm doing, but I've noticed that Spytify doesn't necessarily download all the songs, some songs in a different language (e.g. Chinese) are not downloaded. I often times have to break a playlist of e.g. 700+ songs into multiple smaller playlists, just to account for the crashes with Spytify. If I have a smaller playlist to work with, it's easier for me to identify where I need to resume.

But having a logging feature built in would be nice, I would say esseential for any app. The biggest useful feature for me would be to skip any downloaded songs. Since there is already a setting for duplicating the current track file name, it must already be detecting if a file already exists or not, so I imagine it shouldn't take a few more lines of code to extend that?

**Comment by jwallet** [comment]
for the skip downloaded songs feature, watch the issue #108
