### ISSUE TITLE
Cannot Beerpay

### ISSUE THREAD

**Issue by jumph4x** [jwallet/spy-spotify#119]
**What is the bug ?**
Having a tough time sending you money.

**How to reproduce it or what's the expected behavior ?**
Follow this URL and see that nothing comes up under this project's name: https://beerpay.io/explore?q=spy-spotify%20

Will gladly send PayPal instead.

**Comment by jwallet** [comment]
you search with a space at the end `%20`, `spy-spotify%20` instead of `spy-spotify`, like so https://beerpay.io/explore?q=spy-spotify

**Comment by jumph4x** [comment]
Marking as solved.
