### ISSUE TITLE
Low Quality Embedded Album Art

### ISSUE THREAD

**Issue by Esildor** [jwallet/spy-spotify#126]
**What is the bug ?**
Album art quality sucks

**How to reproduce it or what's the expected behavior ?**
Record a track
open in media player of choice (I'm using mpc-hc)

**Track used**
https://open.spotify.com/track/0ltXEHv2uh7D8aOxzNVOqE?si=OHHh9_JsTGSUcQKn8dH88g

**Screenshots**
![bug](https://user-images.githubusercontent.com/5234969/71141402-0812d980-21e2-11ea-8734-f2ac957ee28f.png)

**Comment by Esildor** [comment]
Also tried it with this song and got no embedded art
https://open.spotify.com/track/09BicNv0aPpTW1Y8A3n8YR?si=oDrC3FmbRL6cj8PY6GMPLw

**Comment by jwallet** [comment]
try using SpotifyAPI instead of the default, see `spytify.exe.config` file 

> Go to https://developer.spotify.com/dashboard/applications/ and register a new application
>    - (e.g.:) Name: spotify, description: none, building: i don't know
>    - Accept the terms
>
> Click on the new spotify application that you created and click on Edit the settings
>    - Set as "Redirect URI" the value "http://localhost:4002", Add and save it.
>
> On the spotify app dashboard, get
>    - The "Client ID"
>    - The "Client Secret"(click on Show)
> Paste the ids below
```

**Comment by jwallet** [comment]
I tried to look if some album covers were missing, but it looked fine on microsoft groove music
![image](https://user-images.githubusercontent.com/23088305/72231392-34273d80-3589-11ea-9970-ebc509417890.png)
and I got all four qualities:
- [small](https://lastfm.freetls.fastly.net/i/u/34s/37fffc97efa3c64badccb08c69f00101.png)
- [medium](https://lastfm.freetls.fastly.net/i/u/64s/37fffc97efa3c64badccb08c69f00101.png)
- [large](https://lastfm.freetls.fastly.net/i/u/174s/37fffc97efa3c64badccb08c69f00101.png)
- [xlarge](https://lastfm.freetls.fastly.net/i/u/300x300/37fffc97efa3c64badccb08c69f00101.png)

You might want to try another player other than MPV
