### ISSUE TITLE
Create sub-folder for album title

### ISSUE THREAD

**Issue by rklrkl** [jwallet/spy-spotify#166]
**What problem will this new feature resolves ?**
When I record multiple albums from a single artist in one session, there's no way for Spytify 1.5 to save each album in a separate sub-folder.

**What feature or enhancement would you like to see added ?**
I would like a checkbox in the settings along the lines of "Create sub-folder for each artist's album". This might also require the "group every artist songs in their own folder" option to be turned on (if it wasn't, you might have to create a folder called "Artist Name - Artist Album" instead of "Artist Name\Artist Album").

My preferred layout (and I suspect a *lot* of people would use this if it was possible in Spytify) is:

Output path\Artist Name\Album Title\Track number Track Title.mp3

All of the above asumes that you can obtain the album title of each track played (I don't know if playing a playlist stops that or not). At the moment, I have to play an album, stop, rename all the created mp3 files into a manually created album folder and then do the next album - not ideal...

---
Want to back this issue? **[Post a bounty on it!](https://issuehunt.io/r/jwallet/spy-spotify/issues/166)** We accept bounties via [IssueHunt](https://issuehunt.io/r/jwallet/spy-spotify).

**Comment by jwallet** [comment]
I still don't get why you need to know how your music is stored, it's a place that nobody cares to look, the upload their music on their phones and they let the music player organize the library for them. After that, they can look at Artist, Album, Playlist, Track, Recently added, Most Played, Live songs, etc...
