### ISSUE TITLE
Remind users to tweak spotify settings for better results

### ISSUE THREAD

**Issue by rklrkl** [jwallet/spy-spotify#168]
**What problem will this new feature resolves ?**
Spotify's default is to autoplay similar tracks (usually from a different artist) immediately after whatever tracks you selected have finished playing. This causes unnecessary tracks to be played/recorded, especially if Spytify is left unattended.

**What feature or enhancement would you like to see added ?**
In the FAQ, I would remind users to turn off the "Autoplay similar songs when your music ends" option, which is right at the very bottom of the user account settings dialogue box in the Windows desktop client.

**Comment by jwallet** [comment]
i was also thinking about informing the user to turn on some quality features from spotify like: `Enabled Audio Normalization` and `Quality: High / Very High` in settings. but there is already documentation from spotify on the subject here:
https://support.spotify.com/is/using_spotify/system_settings/high-quality-streaming/
so I may add it to the faq like you suggested.. will see

**Comment by jwallet** [comment]
fixed with #187 #188
