### ISSUE TITLE
Instructions needed on how to compile from source code

### ISSUE THREAD

**Issue by rklrkl** [jwallet/spy-spotify#169]
**What problem will this new feature resolves ?**
There are often many commits to the project that are later than the last compiled release e.g. as I write this, there are 32 commits in the 13 days since the 1.5 release! This could mean fixes and new features don't get any pre-release testing outside a few hardy souls who work out how to compile the source code themselves.

**What feature or enhancement would you like to see added ?**
Users would still have to build from source code themselves to update to the very latest master release, but step by step instructions would be very welcome indeed. This should include what software dependencies are needed (and what compiler is required) and all the commands required to eventually create the equivalent of what's in each release's .zip file.

Also, if it's possible to cross-compile the project (e.g. on Linux, with Windows as a target) or compile with something other than Visual Studio, it would be nice to have that documented too. After all, Visual Studio is bloatware extraordinaire :-)

**Comment by jwallet** [comment]
1. fork the project to be able to contribute
2. use visual studio 2019
3. build nuggets package
4. you can learn how to use git by searching for tutorials online so you can create a pull request from the forked repo to spytify origin/master
