### ISSUE TITLE
How to record without listening to Spotify

### ISSUE THREAD

**Issue by aNerdgirl** [jwallet/spy-spotify#176]
Hi,
I would like to use spytify for recording podcasts in the background.
Is there a way to mute spotify while recording? If I do it in the normal way, the recording gets muted as well.

Thanks!

**Comment by jwallet** [comment]
to record podcast make sure you check in advanced settings
- [x] Record unknown type tracks detected as an ad

in settings install the Audio Virtual Cable (speaker icon next the audio device)

isolates spotify on the same device using windows Sound Settings > App Volume, after that restart spotify and you won't ear a thing on your default audio device

![image](https://user-images.githubusercontent.com/23088305/73412523-dad44380-42d6-11ea-9bb6-017948bd2770.png)
