### ISSUE TITLE
Spytify 1.5 Keeps Crashing in Windows 10

### ISSUE THREAD

**Issue by riegelstamm** [jwallet/spy-spotify#179]
**What is the bug ?**
> Spytify 1.5 keeps crashing in Windows 10 Pro v1903. It was working beautifully until today. I didn't make any changes to Windows, Spytify, or Spotify.

**How to reproduce it or what's the expected behavior ?**
> Record https://open.spotify.com/album/0AluoLXJeyokj8BwaFZn3k at 160 kbps to MP3 using LastFM API or Sptofy API via VB-Audio Virtual Cable. It records maybe one track or part of a track, and then a window pops up with the message, "Spytify has stopped working."

**Track used**
> https://open.spotify.com/album/0AluoLXJeyokj8BwaFZn3k

Please let me know if I can provide additional information.

**Comment by jwallet** [comment]
is this related #172

**Comment by riegelstamm** [comment]
I don't think so. As I said, I'm using the VB-Audio Virtual Cable, and I've been using it for months without a problem. The problem just started today, even though nothing changed.

**Comment by jwallet** [comment]
I fixed the issue for multiple channels, but it has not been released yet.
So can you paste here the screenshot of your VB-Audio config to see if it's set to stereo, if so I have no idea right now how to resolve it.

![a](https://user-images.githubusercontent.com/23088305/75609052-622df600-5ad3-11ea-8c15-f2b96f567e2d.gif)

**Comment by riegelstamm** [comment]
My VB-Audio was already set to Stereo. In any case, I tried to record the album again today and it worked fine again without crashing, even though I didn't change anything in Spytify, Spotify, or Windows. I guess it was just one of those random things that is impossible to debug.

If Spytify starts crashing again, is there any way to capture a crash log (I mainly use macOS)?

**Comment by jwallet** [comment]
A logger will be added in the upcoming version and you will be able to email me the stack, #181 #182

**Comment by jwallet** [comment]
I also recorded every songs in that album and it worked fine, so i'm going to close it since there is not enough info to investigate the issue deeper.
