### ISSUE TITLE
Certain songs are missing their cover when using SpotifyAPI

### ISSUE THREAD

**Issue by Vaarelsauce** [jwallet/spy-spotify#180]
20% of my songs have missing album/music cover. They sound and work perfectly fine, but if you go to your file explorer and select from Details > Large Icons, some of them just show up the default cover rather than the actual cover. I'll include some pictures.

Some songs that experiences this issue are:
Cheesecake by Billy Marchiafava
DRIP DROP by Jack Harlow
F.Y.I by Alex Wiley, Mick Jenkins
Colorado by Kota the Friend
Night Job by Bas, J. Cole
Whip A Tesla by Yung Gravy, bbno$
Cotton Mouth by DDG

PICTURE 1: The picture I included only has one song with the issue (Cheesecake), because I moved the rest to a different folder and will re-download them again when this bug gets fixed.
![1](https://user-images.githubusercontent.com/36707936/75516887-45e66800-59b2-11ea-8d7b-2c54a3740343.png)

PICTURE 2: Note how the song Bounce has a labeled metadata (cover, album, genre. . .), whereas Cheesecake and DRIP DROP does not have a cover, genre, or anything at all except for the name and the artist. Yet, all three of them sounds perfectly fine.
![2](https://user-images.githubusercontent.com/36707936/75516886-454dd180-59b2-11ea-8eaf-9b58d93ef158.png)

P.S. One cool function that I'd love to see is for Spytify to automatically skip over songs in the Spotify app, so I don't have to manually handpick the "corrupted" songs and put them in a new playlist, then deleting the songs in the music folder, and then re-downloading the corrupted song from the playlist.
Instead, if this function gets added, I can just simply delete the corrupted songs from the music folder, and simply re-download the songs from my existing playlist!

**Comment by jwallet** [comment]
> One cool function that I'd love to see is for Spytify to automatically skip over songs in the Spotify app
the app still does not interact with Spotify app, it could, but it will requires administrator rights to run Spytify, and will probably scares so people to see their Spotify app acts strange while running Spytify. There is an option in Spytify to not record already recorded track, did you try to turn this one off
![image](https://user-images.githubusercontent.com/23088305/75608828-05314080-5ad1-11ea-8d95-15aea6726ccf.png)

> 20% of my songs have missing album/music cover
It's because your songs can't be found on LastFM.API, if you want it to be more accurate you can open, `spytify.exe.config` file and read the commented `// ...` lines that explained how to have Spotify API ready to use in Spytify app. If you use this API, you should get the same cover as the one in Spotify UI.

**Comment by Vaarelsauce** [comment]
Thank you for responding.

>It's because your songs can't be found on LastFM.API, if you want it to be more accurate you can open, spytify.exe.config file and read the commented // ... lines that explained how to have Spotify API ready to use in Spytify app. If you use this API, you should get the same cover as the one in Spotify UI.

So I found something _REALLY_ interesting. Apparently, with Spotify API enabled (tweaked in the text file and all

![image](https://user-images.githubusercontent.com/36707936/75611625-fd719c00-5ad0-11ea-8525-43c61c285479.png)

Spytify did properly downloaded the songs cover correctly. . . .until it **didn't after a while**. Here's a specific example that happened:
- I pressed START on Spytify, after checking all the settings
- A confirmation box for Spotify API popped up on my browser, and then I closed it
- I left the PC on over night, and went to sleep right after turning off both monitors
- When I woke up, I saw my Spotify playlist stopped at the last song that "needed to be downloaded" (previously I deleted the songs without a cover and re-downloaded them again)
-Problem is, after exactly TEN songs, the Spytify seemed to stop uploading the proper cover, and just simply left it blank (although it had no issue downloading the music itself).
Now I have to delete the non-cover song again, and re-download them but this time by micromanaging and try to replicate this issue again, to see if the "10 Song Limit" issue is an actual thing. I'll update right below this sentence when I'm done.

> There is an option in Spytify to not record already recorded track, did you try to turn this one off 
![image](https://user-images.githubusercontent.com/36707936/75611424-36a90c80-5acf-11ea-8afa-18dd1bcb10bb.png)

Yes I do have that disabled, but I'm wondering if there's a feature where instead of Spytify just saying "Skipping song. . .", and then having you wait for, say, 3 minutes or something until the next song is played, I'm suggesting a feature where it automatically skips those 3 minutes and move onto the next song.
This would be extremely helpful if say, you want to download song A and E, but there's a bunch of already downloaded songs like this in the playlist:
- A 3:00 (minutes)
- B 2:00
- C 3:00
- D 3:00
- E 3:00

If you implemented this new Spotify-skip feature, I can simply get song A & E by going through the whole playlist automatically (say, I'm sleeping or busy), and finish downloading in only ~6 minutes, whereas without the feature, I'll have to wait 15 minutes (3 + 2 + 3 + 3 + 3) just to download song A & E, while having to wait for song B-D to finish playing. That's like saving 9 minutes, or **60% of my time** in this specific scenario!

**Comment by martin343** [comment]
> So I found something _REALLY_ interesting. Apparently, with Spotify API enabled (tweaked in the text file and all
> 
> ![image](https://user-images.githubusercontent.com/36707936/75611625-fd719c00-5ad0-11ea-8525-43c61c285479.png)
> 
> Spytify did properly downloaded the songs cover correctly. . . .until it **didn't after a while**. Here's a specific example that happened:
> 
> * I pressed START on Spytify, after checking all the settings
> * A confirmation box for Spotify API popped up on my browser, and then I closed it
> * I left the PC on over night, and went to sleep right after turning off both monitors
> * When I woke up, I saw my Spotify playlist stopped at the last song that "needed to be downloaded" (previously I deleted the songs without a cover and re-downloaded them again)
>   -Problem is, after exactly TEN songs, the Spytify seemed to stop uploading the proper cover, and just simply left it blank (although it had no issue downloading the music itself).
>   Now I have to delete the non-cover song again, and re-download them but this time by micromanaging and try to replicate this issue again, to see if the "10 Song Limit" issue is an actual thing. I'll update right below this sentence when I'm done.
>   **EDIT:** Once again, Spytify stopped using a cover after 10 songs, even though I monitored it this time! Everything was fine until the 10th song!
> 
> ![image](https://user-images.githubusercontent.com/36707936/75612405-e08c9700-5ad7-11ea-81ee-f08968a43c6c.png)
> ![image](https://user-images.githubusercontent.com/36707936/75612457-6b6d9180-5ad8-11ea-9440-0fae702311f8.png)

I can confirm this behaviour. Haven't found a solution yet.

**Comment by jwallet** [comment]
might be related to this issue that I closed ##200

**Comment by jwallet** [comment]
I changed the issue title, the other issues you mentionned were answered earlier or refered to the original issue

**Comment by jwallet** [comment]
spotify api net was missing some validation to renew your user token authorization #202
