### ISSUE TITLE
Constant Volume

### ISSUE THREAD

**Issue by AmazingGabriel16** [jwallet/spy-spotify#183]
**What problem will this new feature resolves ?**
When recording the volume of the recording on spytify will be the same as the volume of the computer/output device. This means that your recording may sound quieter than the actual volume of the song. This new feature will get rid of this problem, therefore you can record your music at max volume without annoying anybody and leaving you to do this anywhere.

**What feature or enhancement would you like to see added ?**
I would like spytify to add a new feature that will allow us to set the volume recording the same level as the spotify volume or get spytify to manipulate the recording volume by taking into consideration our computer volume and multiplying that by a certain percentage to achieve 100%. 

Essentially, though our computer volume may be 2%, spytify will manipulate that volume and achieve 100% by multiplying the sound levels by 50 times.

Or something like that I'm not sure.

However, I do believe that using the Spotify volume is a better way to do it.

Essentially, just let us record our music on mute.

**Comment by jwallet** [comment]
did you try it, it already does that. A quick demo of 1 minute ish:

![image](https://user-images.githubusercontent.com/23088305/75738334-07152280-5cd0-11ea-93d4-54dd0b4adf77.png)

[Beastie Boys - MTL Reppin' For The 514.zip](https://github.com/jwallet/spy-spotify/files/4278989/Beastie.Boys.-.MTL.Reppin.For.The.514.zip)
