### ISSUE TITLE
can it store the art too?

### ISSUE THREAD

**Issue by ageorgios** [jwallet/spy-spotify#19]
Is there a way to store the cd art too?

**Comment by jwallet** [comment]
i can probably work on that, but any decent media player will download it while it plays

**Comment by ageorgios** [comment]
there is itunes that doesnt do it, car media players, so many!
It would be great if you worked on that feature!
Thanks for your work anyways!

**Comment by ageorgios** [comment]
thanks for your work!
Waiting for the compiled release!

**Comment by jwallet** [comment]
last.fm api has limitation so not all song will get infos. i think i will switch to spotify api since i now know how it works, but it will require a refact
