### ISSUE TITLE
Recorded music lacks sound quality

### ISSUE THREAD

**Issue by martin343** [jwallet/spy-spotify#191]
First of all: Great tool, that's exactly what I've been looking for!

**What is the bug ?**
> The recorded files sound different from the streamed music. They are missing clarity/have enhanced lower frequencies.

**How to reproduce it or what's the expected behavior ?**
> I've set Spotify's settings to very high quality (as I use a premium account) and turned normalize on. Also the output quality in Spytify is set to 320. What I listen to directly via the spotify app sounds much better than the recorded files (I use VLC but also cross checked by transferring the mp3s to my phone and using its standard media player). For recording, I use my standard audio device (Realtek High Definition Audio (SST)).

**Track used**
> Spotify track/playlist used : https://open.spotify.com/track/6QunXp3Hfsmz1qRYvILnNE?si=3RwDIBaYTPeFdB2obPal6A (this issue actually counts for every song that I recorded)

**Screenshots**
> I've imported a recorded file into rekordbox (dj software) as well as the same song that i bought on amazon to visualize the waveforms. In the screenshot you can see clearly that the recorded file (the lower waveform) has emphasized bass (red means low frequencies). I've also attached both files so you can hear the difference
![Annotation 2020-03-07 161304](https://user-images.githubusercontent.com/61911962/76145930-8dde4c80-608e-11ea-8463-566c714b43b0.png)
[Desktop.zip](https://github.com/jwallet/spy-spotify/files/4302024/Desktop.zip)

**Comment by jwallet** [comment]
looks like you are not comparing the same track, one is `my name (explicit)` the other one is `my name (feat..)`, if you compare a 90s song vs its remastered version it won't be the same quality. also, the mp3 encoding is not well supported for some laptop or cpu, if you get better results recording in wav format then you have a limitation there. also, the quality can be different when using a different output

**Comment by martin343** [comment]
Okay, I just plugged in an external audio interface and used that as my device. Sounds much better now. Seems like my built-in audio chip is fucked or something. I think we can close this issue now.
