### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by VladimirPittner** [jwallet/spy-spotify#212]
**What is the bug ?**
Metadata is not correct. 
1. If its more then one author of the track, only one is written to metadata
2. Remix info missing in metadata
3. No album cover

**How to reproduce it or what's the expected behavior ?**
Try the track bellow for example and then check ID3v1 or ID3v2. 
It should be something like this:
* Artist: Cream (PL), Deep Fog
* Title: Iridium - Pacco & Rudy B Remix

**Track used**
Spotify track/playlist used : https://open.spotify.com/track/1fCvpfy8SiNjn5XAz5WWVu?si=7xuJJJ3XQTy-NKpAD4hqeA

**Screenshots**
![resultID3](https://user-images.githubusercontent.com/1529181/77698844-fba8d480-6fb9-11ea-96aa-823d783c548b.png)

Thanks

**EDIT:** Works if spotify Api is used to get metadata

**Comment by jwallet** [comment]
yes because spotify and last.fm don't have the same pattern to identify this kind of track. sometimes, last.fm can't find metadata for track that have to specific artist title or song title. in these case use spotifyapi.
