### ISSUE TITLE
The first few hundreds of milliseconds of the song cannot be recorded.

### ISSUE THREAD

**Issue by alankwyu** [jwallet/spy-spotify#215]
**What is the bug ?**
> For those song which starts right away, Spytify fails to record the very beginning.

**How to reproduce it or what's the expected behavior ?**
> Start Spytify. Play that particular song in Spotify. Compare the recording recorded by Spytify and the playing by Spotify desktop app.

**Track used**
> https://open.spotify.com/track/6PJRw5icjh5FnFd7jNUmbG?si=Mh-UdccjS_-ppAhKLRMQGA

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by MapleStoryPSN** [comment]
Have that same issue. The only workaround is to let the track play about 10 seconds and then restart it, followed by editing out that first 10 seconds.
