### ISSUE TITLE
Track naming with brackets and hyphens

### ISSUE THREAD

**Issue by FadamJ** [jwallet/spy-spotify#229]
When populating the song title, it doesn't appear to pick up anything after a " - ", or anything in brackets, although it does pick up content in square brackets. This may be by design, but I've a pointed it at a playlist with a lot or remixes, where this is a common naming convention, and have had to do a lot of manual renaming after importing the files into iTunes.

So, for example, the following song:
https://open.spotify.com/track/185hHr55VlBoBZ0Os6xG3a?si=TetkBR7rTX2MuUYZKp6hkA

Title "Insecurity - Michael Mayer What IZ Love Remix" becomes "Insecurity"

Or this song: https://open.spotify.com/track/5KrhvGD0YF4GgxaQTKv260?si=5tETuMExR42dn3iTtq05GA

Title "Midnight (The Hanging Tree) [Henrik Schwarz Remix]" becomes "Midnight [Henrik Schwarz Remix]"

Other than this minor issue I'm finding this to be a fantastic app, thank you!

**Comment by jwallet** [comment]
the renaming of 
> HOSH - Midnight (The Hanging Tree) (feat. Jalja) - Henrik Schwarz Remix [Extended]

to
> HOSH - Midnight

was supposed to be 
> HOSH - Midnight (The Hanging Tree) (feat. Jalja)

the second part is the extended title
> Henrik Schwarz Remix [Extended]

this would be added as a new id3 tag: `subtitile` so it appears next to the actual title. Many tracks on spotify set the subtitle to provide context and therefore it's not the actual title, like `Remastered`, `Live at ...`

**Comment by FadamJ** [comment]
I wasn't aware of the subtitle tag, will keep an eye on that in future. Thank you!
