### ISSUE TITLE
Add extra tags from SAPI

### ISSUE THREAD

**Issue by brentvh** [jwallet/spy-spotify#233]
Is it possible to add some options for the ID3 tags, such as add BPM (for running playlists) from the spotify API or other parameters (loudness, energy,...).

**Comment by jwallet** [comment]
after taking a look at both api there are no such info available, I got pretty much all info available using spotify api except `AvailableMarkets`, `Restrictions`, `ExternUrls`, `PreviewUrl`, `Id`, `Explicit` which are for their app UI

**Comment by brentvh** [comment]
Hello

(No idea if this reaches you, so please confirm if you received this)

Thanks for your time to look it up, I thought it was possible after seeing another webapp, which could retrieve this info (http://organizeyourmusic.playlistmachinery.com/#).
I tried to look into your code to find something myself, but unfortunately my csharp knowledge is inexistent and I am more into mathematical programming.
I also found some other libraries with a python one, which is quite well documented (https://developer.spotify.com/documentation/web-api/libraries/).

Maybe to come back on this topic, is there a possibility that you could add an advanced option in spytify to add the track id number to the mp3 tag. This way I can maybe create a script on my own to retrieve this information and write it to a txt file. The textfile could be fed into mp3tag to add the info to the tag.

Best regards
Bien à vous (je ne suis pas sûr si tu es anglophone ou francophone, vu que tu habite au Canada 😉)

Brent

**Comment by jwallet** [comment]
yes, when you reply via email it sends your reply in the github thread.
yes, adding the id can be done, but only with spotify api.
maybe just leave all other id3 tags that you will like from the list below, maybe it will be available one day: 
![image](https://user-images.githubusercontent.com/23088305/81618727-fa8b0580-93b5-11ea-81a5-f9edff13ca20.png)
