### ISSUE TITLE
Documentation - Spotify API Usage

### ISSUE THREAD

**Issue by punshonjm** [jwallet/spy-spotify#241]
There is a (disabled) option for Spotify API and keys inside the settings configuration to use the Spotify API. I can also see there is issues created for Spotify integration - what are the steps required to configure it and what will it do? Last FM API for large amounts of the songs I’m trying to use this for are having issues with metadata.

**Comment by jwallet** [comment]
It's in the FAQ: https://jwallet.github.io/spy-spotify/faq.html#media-tags-not-found

**Comment by punshonjm** [comment]
Cheers! Not sure how I missed that.
