### ISSUE TITLE
Issues with the Spotify API

### ISSUE THREAD

**Issue by PhoenixDiscord** [jwallet/spy-spotify#243]
**What is the bug ?**
> A clear and concise description of what the bug is.
> Steps to reproduce the behavior or describe the expected behavior:
After the spying starts and a song starts playing, my browser opens up making a request to `https://accounts.spotify.com/authorize/?client_id=[hidden]&response_type=code&redirect_uri=http://localhost:4002&state=[hidden]&scope=streaming%20playlist-read-collaborative%20user-read-recently-played%20user-read-playback-state%20user-read-currently-playing&show_dialog=True` and the website shows `INVALID_CLIENT: Invalid redirect URI`.

**Track used**
> Spotify track/playlist used : https://open.spotify.com/search
https://open.spotify.com/track/5XjMaXDc3BuWyLszoKZwZU

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![screenshot](https://user-images.githubusercontent.com/37777903/82450747-60aa1380-9aad-11ea-803b-45a1606e45d7.png)

**Comment by PhoenixDiscord** [comment]
After properly whitelisting Spotify I get an error from Spytify itself: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Comment by PhoenixDiscord** [comment]
...but everything works with the error. that's odd.

**Comment by PhoenixDiscord** [comment]
Is this related to the spotify api? The app applied tags from the previous song. 
![img](https://user-images.githubusercontent.com/37777903/82452695-e75ff000-9aaf-11ea-8787-1dbcdeed608b.png)

**Comment by jwallet** [comment]
> 
> 
> After properly whitelisting the url I get an error from Spytify itself: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

firefox does not render json body correctly, use chrome if you want to see the text "You can now close this page"

> Is this related to the spotify api? The app applied tags from the previous song.

your screenshot does not provide any info, the logs can appear in different order, depends when a song starts, ends, finish to encode
