### ISSUE TITLE
FLAC

### ISSUE THREAD

**Issue by JardaH69** [jwallet/spy-spotify#245]
I want to save my music in FLAC (Free Lossless Audio Codec).
Can you add support for this format? Thks :)

**Comment by LetrixZ** [comment]
You could convert the file to FLAC if you want but that will not improve the quality.

**Comment by jwallet** [comment]
flac is lossless from the source it used.

you will still loose some quality from all these steps:
1. spotify.com to your spotify desktop app (spotify encodes its audio to ogg vorbis
> OGG (Ogg Vorbis) at 96 kbps on mobile, 160 kbps for so-called "High" quality on mobile and 320 kbps on mobile and computers for Premium subscribers
2. spotify desktop app to your sound card using windows audio api
3. wasapi to wave buffer
4. wave buffer to MP3/FLAC/WAV....

so unless you really want flac for an obscure reason it won't be what you expect it to be, i guess.

**Comment by doadin** [comment]
@jwallet is it difficult to add? Cause I just discovered this app(Thanks!) and my entire music lib is flac, would be nice to continue this.

**Comment by LetrixZ** [comment]
> @jwallet is it difficult to add? Cause I just discovered this app(Thanks!) and my entire music lib is flac, would be nice to continue this.

The maximun 'quality' you could get from Spotify is equivalent to a 320 Kbps MP3 sound file. You could re-encode that to FLAC but it will not improve quality, you will lose a bit, and it will probably increase the filesize if you use higher bitrates.

**Comment by doadin** [comment]
@LetrixZ I didn't say anything about quality .

**Comment by JakubOrsula** [comment]
@jwallet since spotify finally released lossless streaming maybe this might worth revisiting?
https://newsroom.spotify.com/2025-09-10/lossless-listening-arrives-on-spotify-premium-with-a-richer-more-detailed-listening-experience/
