### ISSUE TITLE
Muting Ads leaves a bit of ad left

### ISSUE THREAD

**Issue by FREAKINGFROZENBRACKETS** [jwallet/spy-spotify#247]
Literally the title. When it silences the ads it always leaves .5 seconds of the ad left on the recording

**Comment by jwallet** [comment]
sadly spytify depends on spotify TrackChanged events that are sometimes not accurate, there is not much to do here https://jwallet.github.io/spy-spotify/faq.html#track-overlap-on-recorded-track
