### ISSUE TITLE
Multiple artists not always included in filename

### ISSUE THREAD

**Issue by jeremyhallden** [jwallet/spy-spotify#249]
Record https://open.spotify.com/album/71zUTTe2MisUVCoioFliJt?highlight=spotify:track:6HDUUP2LvQjsGCJ7TGNh6H

The artists are "Tristan" and "Raja Ram" and the track name is "Take a Trip".
The output filename should probably be "Tristan & Raja Ram - Take a Trip" (or "Tristan, Raja Ram - Take a Trip")
The output filename today is "Tristan - Take a Trip"

It is worth noting that things could get a bit messier (often with electronic music) when the track is a remix by another artist (depending on the API) i.e. "Artist A - Track (Artist B remix)". If the API used returns "Artist A" & "Artist B" as artists, as I think I remember that the spotify API returns, the output filename should _not_ be "Artist A & Artist B - Track (Artist B remix)".

I hope that this is understandable :)

**Comment by jwallet** [comment]
the info comes from spotify
![image](https://user-images.githubusercontent.com/23088305/84330829-71065900-ab56-11ea-8e0e-b7de177dab15.png)

you can give a try to spotify.api

**Comment by jeremyhallden** [comment]
I have tried the API (a .net wrapper) and I get the artists as an array with the two correct entries.

**Comment by xqzba** [comment]
Also getting this. Switched to Spotify API and getting same result. I think the other artists should just be added to the "Contributing Artists" tag instead.

**Comment by jeremyhallden** [comment]
> Also getting this. Switched to Spotify API and getting same result. I think the other artists should just be added to the "Contributing Artists" tag instead.

One of the artists is not more "primary" than the other. See the title on discogs for example.
"Tristan, Raja Ram - Take A Trip"

https://www.discogs.com/Raja-Ram-Raja-Rams-Stash-Bag-Vol-6/release/11591789

**Comment by jwallet** [comment]
your issue is not an actual, since the feature you are asking for has never been applied yet.
https://github.com/jwallet/spy-spotify/issues/137

**Comment by jwallet** [comment]
coming next version;
if you use spotify api, you will get album artists in the file name;
album artists are provided by spotify;
performers will still only appears in metadata as performers;
![image](https://user-images.githubusercontent.com/23088305/90086088-98f57280-dce7-11ea-9f88-340c872d84fa.png)

**Comment by jeremyhallden** [comment]
> coming next version;
> if you use spotify api, you will get album artists in the file name;
> album artists are provided by spotify;
> performers will still only appears in metadata as performers;
> ![image](https://user-images.githubusercontent.com/23088305/90086088-98f57280-dce7-11ea-9f88-340c872d84fa.png)

Thanks! :)
