### ISSUE TITLE
audio delay when starting to record

### ISSUE THREAD

**Issue by ZigZigis** [jwallet/spy-spotify#251]
When I finish the recording I can hear a delay when the music starts, it's about 0.5 seconds.

**Track used**
> Spotify track/playlist used : https://open.spotify.com/track/3sjeJR1dT80UuzDuvk1Cij?si=Ktj2ZB23Shu12vHv8cve5A

**Comment by toenuff** [comment]
Same issue here.  First time using it. I tried 1.6 and same thing.
