### ISSUE TITLE
Feature request: retrieve release_date from Spotify and add to track metadata

### ISSUE THREAD

**Issue by AlexJFox** [jwallet/spy-spotify#253]
I'd like Spytify to be able to add the original release date of the recording to the track metadata. The Spotify API seems to support this. Would you consider adding?

Thanks!

**Comment by jwallet** [comment]
it's already there, using the only official id3 tag available `Year`.
![image](https://user-images.githubusercontent.com/23088305/90088165-584c2800-dcec-11ea-8f64-6d682461d8fc.png)
if you use spotify.api it will get the Year of `releaseDate`
