### ISSUE TITLE
Wrong metadata used

### ISSUE THREAD

**Issue by alankwyu** [jwallet/spy-spotify#272]
**What is the bug ?**
> Wrong metadata used.
> Steps to reproduce the behavior or describe the expected behavior:
Desktop and web version show the Star Wars song correctly. Spytify downloads a Harry Potter album art and saves it in Harry Potter directory instead.

**Track used**
> Spotify track/playlist used : https://open.spotify.com/track/1lL5wgXpI3Wwn6Am13dQIj?si=24at9XDHR_-E1UEd7sppvw

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![Screenshot 2020-10-22 114955](https://user-images.githubusercontent.com/29901059/96897740-eebf6700-145c-11eb-95ba-91df1fab5b6a.jpg)

**Comment by Frontear** [comment]
By any chance, have you tried using the Spotify API instead of LastFM API?

**Comment by alankwyu** [comment]
Just tried Spotify API, it is using the correct Star Wars metadata.

**Comment by Frontear** [comment]
This could honestly be LastFM specific to be completely honest. It's still quite odd it pulls metadata that is so unbelievably far from what is expected though.

**Comment by jwallet** [comment]
indeed, in the future i might make spotify api the default, even with that annoying pop up that ask to log in.
