### ISSUE TITLE
Does not work if you have 7.1 Headphones 

### ISSUE THREAD

**Issue by P4R4NORM4L** [jwallet/spy-spotify#275]
**What is the bug ?**
> Basically, trying to record the song in 320kbps (premium) I get this message.
`Error while recording: Recording multi-channel files is not supported (6 channels), reduce the number of channels to 2 (stereo) or 1 (mono).`
If I switch it to Wav Format the message dissapears, but the file does not save. This is the message I get. `Error while recording: Unknown exception: Must read complete blocks: requested 81920, block align is 24`
> Have a USB Headset which is 7.1 Like my Astro A40TR and try recording  

**Track used**
> All tracks, it doesn't matter.

**Comment by jwallet** [comment]
should be fixed in the upcoming version
