### ISSUE TITLE
Multichannel Audio Fallback not working

### ISSUE THREAD

**Issue by Davbra98** [jwallet/spy-spotify#295]
**What is the bug ?**
The Multichannel Audio Fallback to stereo is not working. Instead of crashing now after logging that it falls back to stereo the recording does not work.
![grafik](https://user-images.githubusercontent.com/16635620/103202584-1a464e00-48f3-11eb-94c0-cb4f2bb91f06.png)
I checked out the source and in VisualStudio there is an Exception being thrown in the NAudio.dll when calling _waveIn.StartRecording(); As in this Screenshot:
 
![grafik](https://user-images.githubusercontent.com/16635620/103205238-68f6e680-48f9-11eb-86a2-3431a0145e28.png)

The translated message is Not implemented.

**Track used**
This happens regardless of the track

Installing the virtual cable works but I can't listen to the tracks while they are recorded.

**Comment by jwallet** [comment]
the fallback works when encoding not recording. the issue comes from naudio api
```
private ISampleProvider ConvertToRightChannelCount(ISampleProvider input)
    {
        if (input.WaveFormat.Channels == mixer.WaveFormat.Channels)
        {
            return input;
        }
        if (input.WaveFormat.Channels == 1 && mixer.WaveFormat.Channels == 2)
        {
            return new MonoToStereoSampleProvider(input);
        }
        throw new NotImplementedException("Not yet implemented this channel count conversion");
    }
```
your mixer should always be the same as the audio device output. otherwise it will throw.
maybe you can change to another audio device. this exception should also happens to you when recording to `.wav`

**Comment by Davbra98** [comment]
Thanks for your fast answer.
I think I know what is happening now.
First about my setup (I maybe should have mentioned this in my original post):
I have 2 stereo speakers connected to my ASUS STRIX Raid DLX soundcard. I also have my headphones connected to that soundcard.

I have set every setting I could find to stereo but somehow it still gets detected as 8 channel audio.
Looking at the code from the post above the problem seems to be that the input is recognised as 8 channel but the mixer recognises it as 2 channel. As mentioned before this is indeed an NAudio problem and needs to be fixed on NAudio's side.

However I'm actually testing a workaround which seems to work.
If I set my output from stereo to 7.1 (either in the soundcard settings or in windows) NAudio is able to start the recording. Spotify seems to be outputting 2 channel audio anyway regardless of the setup. I tested it with one song now and the record sounded good.

The reason why I actually don't like to record to any other output devices is because I want to listen to the music while it's playing and let the recorder run in the background.

**Comment by jwallet** [comment]
If you record to `.wav` it should keep all channels, otherwise as we know `.mp3` is limited to 2 channels and a sample rate of 44kHz, that's how the codec is

**Comment by Davbra98** [comment]
The reduction of channels is not the problem. Spotify only use stereo even if you have it set to 7.1.

I actually found the solution for my problem not being able to listen to the music while it's being recordered on the Virtual Cable Output. 
When you install the virtual cable driver it actually creates two audio devices. One device as speaker and one as microphone. While playing on the speaker the output is also routed to the microphone.
![grafik](https://user-images.githubusercontent.com/16635620/103274352-c22a4d00-49c1-11eb-9abc-6894dc0f1744.png)

The solution to now listen to it while playing is to go into the microphone settings and check use this device as audio source. In the Dropdown then you can pick the device that the audio should be played back on.
![grafik](https://user-images.githubusercontent.com/16635620/103274491-17fef500-49c2-11eb-82e5-1727838c4779.png)

@jwallet  Maybe you should put this somewhere in the FAQ section

This issue now can be closed.

**Comment by jwallet** [comment]
sounds good thanks
I'm wondering if you just hear the device, or it acts as your new source now, so will it record youtube in the background?

**Comment by Davbra98** [comment]
I tested this right now playing youtube in the background and it works as it should. The playback device stays the Virtual Cable Output but the audio is also getting routed to the speakers.  As soon as I click Spy in Spytify everything but Spotify gets muted and does not appear in the recording. So it works even if you have Youtube or other sound outputs in the background.

However as everything but Spotify is muted you can also only hear Spotify over the speakers. If you want to hear Youtube and Spotify over your speakers but only record Spotify you can set the output device for your Browser to your speakers in the settings. Make sure Spytify is actually recording on the Virtual Cable and your listening to the Virtual Calble mic too. Then you can hear both. Even if I don't know why someone would want this it's possible.

I hope this was understandable.

**Comment by jwallet** [comment]
yes, do you see something to change, I just updated it with your suggestion http://localhost:4000/spy-spotify/faq.html#listen-to-virtual-device

**Comment by Davbra98** [comment]
Great.
Just a small correction. In the Screenshot you have the Default Playback Device selected in the dropdown. The problem with that is when you switch to the Virtual Cable the default device will be the  Virtual Cable too and you will still hear nothing.

I would suggest adding a sentence like:
`Then in the dropdown "Playback through this device" select your output device.`
Maybe you also change the screenshot to show that propperly.

Thanks for the great and fast support
And of course for the great software you provide

**Comment by jwallet** [comment]
thanks, it's updated
