### ISSUE TITLE
Not Recording When Using Spotify Metadata

### ISSUE THREAD

**Issue by AyrtonB** [jwallet/spy-spotify#307]
**What is the bug ?**
Everything works absolutely fine when using the LastFM API for metadata retrieval, however when I switch to using the Spotify API the tracks no longer record. I know the Spotify API credentials are correct as I'm using them in other applications with no problems. When using the Spotify API I get a redirect error `INVALID_CLIENT: Invalid redirect URI` but as I understand it that is related to my app redirect rather than anything on the Spytify end.

**Screenshots**
Example of rediirect error
![image](https://user-images.githubusercontent.com/29051639/103458060-5b2bd180-4cfc-11eb-8276-fe21963742c1.png)

Example showing trsck playing but not recording (previous recordings occured when LastFM API was selected)
![image](https://user-images.githubusercontent.com/29051639/103458007-dc369900-4cfb-11eb-8b56-8fdc641febd0.png)

**Comment by Davbra98** [comment]
Did you set the redirect URI in your Spotify API Application ? If not you can edit it in your application by clicking on edit settings
![grafik](https://user-images.githubusercontent.com/16635620/103487728-cadab300-4e07-11eb-9fd7-2785fa96a162.png)

**Comment by Cirromulus** [comment]
I have the same problem. After adding the correct redirect URI, Spotify lets me add the custom app, and Spytify seems to know the correct name. However, it does not detect existing files and does not create a recording (does not even create the folder).
Also, after every track, it presents an error message, that it can't find the `.spytify` file.

**Comment by AyrtonB** [comment]
Thank you that fixed it! I previously had a redirect but the 4002 one which seems to have fixed everything.

**Comment by jwallet** [comment]
> 
> 
> I have the same problem. After adding the correct redirect URI, Spotify lets me add the custom app, and Spytify seems to know the correct name. However, it does not detect existing files and does not create a recording (does not even create the folder).
> Also, after every track, it presents an error message, that it can't find the `.spytify` file.

related to #310 

I would like to know how you got that issue, I can't find the real reason of this bug.
- does this happen using lastfm api?
- do you allow the app on the wrong connected spotify account?
- which track are you playing ? https://open.spotify.com

**Comment by Cirromulus** [comment]
I think I will discuss this in #310 (which is actually my auto-bugreport) or a new Issue, because I tested it now.
This happens with last.fm API as well, and with every track.
I switched back to 1.7, where it works both with spotify and last.fm API.
Maybe it has something to do with the fact that my music is located in a samba share?
