### ISSUE TITLE
Report: Part of the path ..\Untitled\.spytify could not be found.

### ISSUE THREAD

**Issue by jwallet** [jwallet/spy-spotify#310]
#Exception Report

**Application**: Spytify  
**Version**:     1.8.0.0  
**Region**:        
**Date**: 02.01.2021  
**Time**: 12:07  

**Error Message**: Ein Teil des Pfades &quot;\\BLOCKFISCH\Musik\Spotifyrip\Spotify Premium\Untitled\.spytify&quot; konnte nicht gefunden werden.
 
##Stack Traces
```text
Top-level Exception
Type:    System.IO.DirectoryNotFoundException
Message: Ein Teil des Pfades &quot;\\BLOCKFISCH\Musik\Spotifyrip\Spotify Premium\Untitled\.spytify&quot; konnte nicht gefunden werden.
Source:  mscorlib
Stack Trace: bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   bei NAudio.Lame.LameMP3FileWriter..ctor(String outFileName, WaveFormat format, LAMEPreset quality, ID3TagData id3)
   bei EspionSpotify.Recorder.GetFileWriter()
   bei EspionSpotify.Recorder.&lt;WaveIn_RecordingStopped&gt;d__32.MoveNext()
 
```
 
##Assembly References
 - ExceptionReporter.NET, Version=4.0.2.0  
 - MetroFramework, Version=1.4.0.0  
 - mscorlib, Version=4.0.0.0  
 - NAudio, Version=1.9.0.0  
 - NAudio.Lame, Version=1.0.9.26885  
 - Newtonsoft.Json, Version=12.0.0.0  
 - PCLWebUtility, Version=1.0.0.0  
 - SpotifyAPI.Web, Version=1.0.0.0  
 - SpotifyAPI.Web.Auth, Version=1.0.0.0  
 - Spytify, Version=1.8.0.0  
 - System, Version=4.0.0.0  
 - System.Core, Version=4.0.0.0  
 - System.Drawing, Version=4.0.0.0  
 - System.IO.Abstractions, Version=7.0.0.0  
 - System.Net.Http, Version=4.2.0.0  
 - System.ValueTuple, Version=4.0.2.0  
 - System.Windows.Forms, Version=4.0.0.0  
 - System.Xml, Version=4.0.0.0  
 - TagLibSharp, Version=2.2.0.0  

##System Info  
```test
Operating System
-Microsoft Windows 10 Pro
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = 60
--FreePhysicalMemory = 22945492
--OSArchitecture = 64-Bit
--OSLanguage = 1031
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.18363

Machine
-MONSTER
--Manufacturer = Gigabyte Technology Co., Ltd.
--Model = X570 AORUS ELITE
--TotalPhysicalMemory = 34303541248


```

**Comment by jwallet** [comment]
@Cirromulus can you add screenshots of the app to see your settings, like all tabs, you can hide your output path if you wish

**Comment by Cirromulus** [comment]
![image](https://user-images.githubusercontent.com/7480344/103660490-f11a6300-4f6d-11eb-98dd-724ff491b158.png)
Settings (migrated from version v1.7, where it works):

![image](https://user-images.githubusercontent.com/7480344/103660591-10b18b80-4f6e-11eb-95b3-5c450f11e19e.png)
![image](https://user-images.githubusercontent.com/7480344/103660625-19a25d00-4f6e-11eb-96d1-9bcd55caff67.png)

Note that the error still happens when the target folder already exists, but a new song of the album was to be recorded. 
The actual song is not being saved as well.
