### ISSUE TITLE
Tracks start recording a bit too late

### ISSUE THREAD

**Issue by elguaxo** [jwallet/spy-spotify#32]
I'm trying the new Spytify v1 and now it seems that tracks start recording maybe one or 2 seconds too late.

Thanks in advance!

**Comment by jwallet** [comment]
the api seems to be a bit late when skipping a song, leaving it on should record the proper length, can you provide the songs you were trying: the actual song and the one before

**Comment by elguaxo** [comment]
It was on the first track (which is not so important in this particular case), but I also noticed it on some of the next tracks:

https://open.spotify.com/album/7bgrOEPe5XRSeolrGXrgm6?si=3TpAniLwTIqTGN4m8H9c6w

I am interested mostly in recording audiobooks. When the end of a track and the beginning of the next track are the end and beginning of a chapter of the book, there is no problem, since there is usually a small pause and you don't notice if a track stops too soon or begins a little late. But many times this is not the case, and the narrator speaks up to the last second of a track and/or begins during the first second of a track.

**Comment by MCCMikey** [comment]
I've experienced the same problem on my Windows 8.1 machine. There's a two second lag between the track starting, and the API reporting it. I think you'd need a silence detection and a pre-record to get around it.

**Comment by MCCMikey** [comment]
Out of curiosity, I loaded Spotify and Spytify into a Windows 10 virtual machine, using a new Spotify account. Same problem, so it isn't related to other devices on the account.

**Comment by jwallet** [comment]
make sure that you don't set the bitrate quality over Spotify Free Quality if you don't have premium.

**Comment by SiMoZ-287** [comment]
I have this problem too! I have Spotify premium but I still have a delay in every song. If you need some help I can providing logs or doing beta testing or something else. I need your app beacuse in my car I can't switch songs from my wheel using spotify, it only works with mp3 on an usb stick. Can you provide a download for the older version while you're fixing it?

**Comment by jwallet** [comment]
[all releases](https://github.com/jwallet/spy-spotify/releases)

**Comment by jwallet** [comment]
i refactored some code, i'm not sure if it will be better since I don't get the issue you guys got, i might need to find a tool to simulate a slow connection to found out the real issue here

**Comment by jwallet** [comment]
ok guys i found the issue

**Comment by jwallet** [comment]
Don't forget to leave some feedback

**Comment by elguaxo** [comment]
Spytify v1.0.0.1 works perfect! No more delays. :+1:

**Comment by MCCMikey** [comment]
I've left it running for a few days and check on the result now and then. Seems to be working quite well now :)
