### ISSUE TITLE
Installation package / update

### ISSUE THREAD

**Issue by kyds3k** [jwallet/spy-spotify#343]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2411%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/jwallet/spy-spotify/issues/343)

Would be nice to have an installation package and the ability to update the app from the app without making a new folder every time!

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $11.00)

- [<img src='https://avatars.githubusercontent.com/u/23088305?v=4' alt='jwallet' width=24 height=24> jwallet](https://issuehunt.io/u/jwallet) ($1.00)
- $10.00 have been anonymously funded.
### Submitted pull Requests
- [#356 add basic updating functionality](https://issuehunt.io/r/jwallet/spy-spotify/pull/356)
- [#363 Updater](https://issuehunt.io/r/jwallet/spy-spotify/pull/363)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/jwallet/spy-spotify/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by jwallet** [comment]
I contacted IssueHunt, looks like I cannot reward a PR, I can only refund (but some complaint about never being proceeded) 
![image](https://user-images.githubusercontent.com/23088305/124048794-1b148580-d9e5-11eb-9405-749a3deeb81b.png)

**Comment by Davbra98** [comment]
> 
> 
> I contacted IssueHunt, looks like I cannot reward a PR, I can only refund (but some complaint about never being proceeded)
> ![image](https://user-images.githubusercontent.com/23088305/124048794-1b148580-d9e5-11eb-9405-749a3deeb81b.png)
> https://spectrum.chat/issuehunt/discussion/how-can-i-reward-a-pr-that-has-no-reward-button-but-has-a-refund-fundings-button-owner~4dd62bdf-f354-43dd-aaf5-414ccfd09f87

You should keep it. I see that you put a lot of work and time into this project which is awesome. So in my opinion this is your reward for it and you should totally keep it.

**Comment by jwallet** [comment]
thanks, so I'm gonna wait the fix the issue, otherwise it's money lost

**Comment by jwallet** [comment]
I had to deposit $1 to fix the issue status from "unfunded" to "funded", damn I love bugs, even more when it's related to my money
