### ISSUE TITLE
A "Spotify Premium.mp3" is often created among the recordings

### ISSUE THREAD

**Issue by kaleidocore** [jwallet/spy-spotify#345]
**What is the bug ?**
Often (but not always?) when recording a new session Spytify creates a 1-second long "Spotify Premium.mp3" in the output folder. This is obviously not an actual track in the playlist, and even if it were it ought to be automatically discarded by the minimum-30-seconds rule.
I typically notice this file after doing an overnight recording of some audio book, i.e. many small tracks (~1-3 min) in a 2h playlist or so. It is however entirely possible that this file pops up more-or-less immediately at play/resume. 
FWIW, I _do_ have Spotify Premium, I suspect Spytify  outputs this as some sort of diagnostics?

**Track used**
I've seen this file show up among my recordings many times - this should be easily reproducible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22889446/107946462-5744cd80-6f91-11eb-99df-b48d77356dc5.png)

**Comment by jwallet** [comment]
thanks I dont have premium so i did not have the chance to try that. I will look at it.

**Comment by jwallet** [comment]
https://github.com/jwallet/spy-spotify/blob/master/EspionSpotify/Spotify/SpotifyStatus.cs#L12

should contains `Constants.SpotifyPremium`
