### ISSUE TITLE
Option to choose Wav 16 bit (1440kbps) instead of default Wav 32bit (2880kbps).

### ISSUE THREAD

**Issue by barryxkeogh** [jwallet/spy-spotify#346]
Hi,

When selecting WAV as the audio format in Spytify, a larger 32bit (2880kbps) WAV file is created rather than a 16bit (1440kbps) file.

Could an option be added to give a choice of WAV16 (1440kbps) also rather than just the default WAV32 (2880kbps) ?

Many thanks,

Barry.

**Comment by jwallet** [comment]
wav quality is based on your audio device default format, if you have a file with a bitrate of 2880kbps I guess you have a default format of CD Quality. You can decrease this format in "Sounds" panel, select your "device" and go to the "advanced" tab. You will find "Sounds" in the contextual menu of the Sound Icon in the Windows Taskbar.

For instance, if you reduce the quality tot "Telephone Quality" `8 bit, 11025 Hz` you will end up with a bitrate of 512

**Comment by jwallet** [comment]
I will investigate it further, looks like it actually comes from nAudio lib, it set a 32 bits wave file by default and converting it to 16 bits does not fix it. 

closing in favor of issue : #409
