### ISSUE TITLE
Spotify didn't connect to the local API, please try again.

### ISSUE THREAD

**Issue by LordOfPolls** [jwallet/spy-spotify#35]
**What is the bug ?**
"Spotify didn't connect to the local API, please try again."
Spytify is unable to connect to the "local api" regardless of what ive tried;
1- Running spotify with admin
2- Running EspionSpotify.exe with admin
3- Rebooting
4- Running on a second machine
5- Using the windows 10 app for spotify
6- Using the desktop exe app for spotify
7- Changing firewall settings for both Spytify and Spotify
8- Disabling the firewall outright

**How to reproduce it or what's the expected behavior ?**
>Open EspionSpotify.exe
>Press start

**Screenshots**
![image](https://user-images.githubusercontent.com/22540825/42895236-2ee8d9d4-8ab1-11e8-8127-0068b15f5b22.png)

**Comment by LordOfPolls** [comment]
After some testing, the last version to connect to the api was V1
The last version to record was 0.810

**Comment by beatz2** [comment]
I have the same issue, any solution so far? :(

**Comment by DerFisc** [comment]
> After some testing, the last version to connect to the api was V1
> The last version to record was 0.810

I'm pretty sure I was able to record with Spytify v1.0.1 and the Windows 10 app some days ago.
But now it doesn't work for me as well.

**Comment by DavidViggiano** [comment]
I also have the same issue.  v1.0.1 and Spotify 1.0.85.259.g4ab01679.  I'll try digging into the application after a couple of meetings this morning.  This seems a lot more fun than work.

**Comment by DavidViggiano** [comment]
It's a known issue with SpotifyAPI:  https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/254

I assume there will be an updated version shortly.  You can use the assembly, or wait for spy-spotify to be updated.

**Comment by GerryHarrison** [comment]
Same issue here...hope it will be resolved soon!

**Comment by jwallet** [comment]
For anyone interested, I'm using Spotify available in Windows Store, there is a difference between the exe available online and the one in the store. I'm not saying it will work for you, but I have no issue atm... I did not about this issue until now, so I will look at it this week

**Comment by jwallet** [comment]
This is related to SpotifyAPINET, it looks like they will let the local API go, so I will have to use another way to connect to the Spotify app, Like @LordOfPolls said the only version that still records is the one before adding the Spotify API, [0.810](https://github.com/jwallet/spy-spotify/releases/tag/0.810)

**Comment by stebo02** [comment]
Ez-blocker also stopped working, probably because of the same reason. Is there maybe a way to download the old version of the spotify API and use that one instead?

**Comment by jwallet** [comment]
nope after the Spotify updates nothing works anymore, they mainly removed the way we used to get an oauth token, now every request needs a proper account and a valid auth_id token. Unless if someone with too much spare time dives into it and find how we get new authentification from Spotify (secret header) we won't get so far..

I think every project that was using this trick are now refactoring their project. So do I

**Comment by mmartain** [comment]
Yeah, i'm going to look into adding a mod to https://github.com/khanhas/Spicetify to send track info into spy client
