### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by supsm** [jwallet/spy-spotify#352]
**What is the bug ?**
The README has different audio qualities listed.  
Right before the first image in the third paragraph it says
> A free Spotify account will work, but restricts audio quality to **120** kbps  

However on the third paragraph in **How it works**, it says  
> Spotify Free **160**kbps, Spotify Premium 320kbps  

In the app the quality is 160 kbps for spotify free.  

**Screenshots**
> If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/60897356/113536948-2abe3280-958c-11eb-9b28-2db39ba4bb1c.png)
![image](https://user-images.githubusercontent.com/60897356/113536972-3873b800-958c-11eb-8c0c-bc190ba9464d.png)
![image](https://user-images.githubusercontent.com/60897356/113536988-44f81080-958c-11eb-8f6f-1257f8c7e245.png)

**Comment by supsm** [comment]
Also, it says
> Gets and records with the same great audio quality than Spotify  

which doesn't make grammatical sense. It should be "Gets and records with the same great audio quality **as** Spotify"

**Comment by jwallet** [comment]
Thanks, if you see any other mistakes feel free to report them, you might find many, I don't frequently speak/type English.
