### ISSUE TITLE
Apps opened after spytify starts recording will not be silenced

### ISSUE THREAD

**Issue by supsm** [jwallet/spy-spotify#353]
**What is the bug ?**
Spytify has a feature to mute other apps' sounds, but if an app is opened after spytify starts recording, it will not be silenced.  
To reproduce, start spytify recording, then open an app that outputs sound.  

**Screenshots**
![image](https://user-images.githubusercontent.com/60897356/113537514-ca2ff500-958d-11eb-8c4d-9da320a4253e.png)
Everything except for spotify and spytify are muted, however the rightmost app is not muted since it was opened after spytify started recording

**Comment by jwallet** [comment]
it's actually a limitation, spytify mutes all others apps when clicking on start recording, it would just be too much to have a background process that keeps muting apps as soon as they are playing sounds. normally you want to set up both spotify and spytify on a separate audio device and start the recording session there, so away from any other background sounds.

see the how to [use spytify section](https://jwallet.github.io/spy-spotify/overview.html#how-to-use-it)
