### ISSUE TITLE
Spotify API does not pop up until song starts playing

### ISSUE THREAD

**Issue by supsm** [jwallet/spy-spotify#354]
**What is the bug ?**
> A clear and concise description of what the bug is.

The window to authorize spytify does not appear until I unpause the song, when it is usually supposed to record.
> Steps to reproduce the behavior or describe the expected behavior:

Start Spotify and Spytify  
Pause the song on Spotify  
Start spying (using spotify api)  
Unpause the song  

**Track used**
> Spotify track/playlist used : https://open.spotify.com/search

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by jwallet** [comment]
like this? do you use the latest release ?

![spytify](https://user-images.githubusercontent.com/23088305/114315591-a1e45100-9acd-11eb-9e92-e7974d7765c6.gif)

**Comment by supsm** [comment]
Yes, I was using the latest release... I'm not sure why that happens for me though...

https://user-images.githubusercontent.com/60897356/114315792-58880780-9ab5-11eb-91fc-404226e4da22.mp4

**Comment by supsm** [comment]
Hmm... I'm not able to reproduce this anymore... I'll close this for now, and reopen it when it happens again.

**Comment by jwallet** [comment]
keep in mind spytify has no control on Spotify app, so if you can see Spotify app in here 👇, it means Spytify has no session to record from.
> Right click on Sound icon in the taskbar > Sound Settings > App volume and device preferences (in Advanced sound options)
![image](https://user-images.githubusercontent.com/23088305/114316655-6b5d0500-9ad2-11eb-80d6-b4f039b00524.png)

**Comment by jwallet** [comment]
if your token was still valid it might still use it, so it won't sow the login page, it will still record using the spotify api.
also, if you have multiple accounts, and you logged in the wrong one, the token will be valid, but it won't be able to detect the current track since your other account does not play any song.
