### ISSUE TITLE
It stopped working, can't initialize

### ISSUE THREAD

**Issue by OverPT** [jwallet/spy-spotify#355]
**What is the bug ?**
> A clear and concise description of what the bug is.

I left Spytify recording a few tracks, when I came back, it was "frozen" in the middle of the third track (it should be on the 8 or 9th track, by that time). Clicking start/stop button did nothing (still switched between start/stop, but it didn't anything). When I tried to close it, it froze. Even going to task manager to kill it, I could still see it in the windows bar. Spotify also crashed. I couldn't get rid of both Spytify and Spotify, so I did a hard reset. 

Now, everytime I try to lauch Spytify, it crashes at launch, with the message "Operation Failed". I've tried to delete it and redownload again, but the error still happens (I'll copy the details below). Spotify is working as usual, so is my system, the problem is only Spytify.

#Exception Report

**Application**: Spytify  
**Version**:     1.9.0.0  
**Region**:        
**Date**: 16/04/2021  
**Time**: 08:26  

**Error Message**: Falha de inicializa&#231;&#227;o do sistema de configura&#231;&#227;o
 
##Stack Traces
```text
Top-level Exception
Type:    System.Configuration.ConfigurationErrorsException
Message: Falha de inicializa&#231;&#227;o do sistema de configura&#231;&#227;o
Source:  System.Configuration
Stack Trace: em System.Configuration.ConfigurationManager.PrepareConfigSystem()
   em System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   em System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   em System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   em System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   em System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   em System.Configuration.SettingsBase.get_Item(String propertyName)
   em System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   em System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   em EspionSpotify.Properties.Settings.get_app_console_logs()
   em EspionSpotify.Program.ReportException(Exception ex)
Inner Exception 1
Type:    System.Configuration.ConfigurationErrorsException
Message: '.', valor hexadecimal 0x00, &#233; um car&#225;ter inv&#225;lido. Linha 14, posi&#231;&#227;o 1. (C:\Users\User\AppData\Local\Spytify\Spytify.exe_Url_elexbiww4ydazfxaq1nudgyxcdoiyzgp\1.9.0.0\user.config line 14)
Source:  System.Configuration
Stack Trace: em System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   em System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   em System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
Inner Exception 2
Type:    System.Xml.XmlException
Message: '.', valor hexadecimal 0x00, &#233; um car&#225;ter inv&#225;lido. Linha 14, posi&#231;&#227;o 1.
Source:  System.Xml
Stack Trace: em System.Xml.XmlTextReaderImpl.Throw(Exception e)
   em System.Xml.XmlTextReaderImpl.ParseText(Int32&amp; startPos, Int32&amp; endPos, Int32&amp; outOrChars)
   em System.Xml.XmlTextReaderImpl.ParseText()
   em System.Xml.XmlTextReaderImpl.ParseElementContent()
   em System.Xml.XmlTextReaderImpl.Skip()
   em System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)
   em System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   em System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   em System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   em System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
 
```
 
##Assembly References
 - ExceptionReporter.NET, Version=4.0.2.0  
 - MetroFramework, Version=1.4.0.0  
 - mscorlib, Version=4.0.0.0  
 - NAudio, Version=1.10.0.0  
 - NAudio.Lame, Version=1.1.6.0  
 - Newtonsoft.Json, Version=12.0.0.0  
 - PCLWebUtility, Version=1.0.0.0  
 - SpotifyAPI.Web, Version=1.0.0.0  
 - SpotifyAPI.Web.Auth, Version=1.0.0.0  
 - Spytify, Version=1.9.0.0  
 - System, Version=4.0.0.0  
 - System.Core, Version=4.0.0.0  
 - System.Drawing, Version=4.0.0.0  
 - System.IO.Abstractions, Version=13.0.0.0  
 - System.Net.Http, Version=4.2.0.0  
 - System.ValueTuple, Version=4.0.2.0  
 - System.Windows.Forms, Version=4.0.0.0  
 - System.Xml, Version=4.0.0.0  
 - TagLibSharp, Version=2.2.0.0  

##System Info  
```test
Operating System
-Microsoft Windows 10 Home
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = 60
--FreePhysicalMemory = 27895708
--OSArchitecture = 64 bits
--OSLanguage = 2070
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.19042

Machine
-DESKTOP-L1VVPJ6
--Manufacturer = Micro-Star International Co., Ltd.
--Model = MS-7C79
--TotalPhysicalMemory = 34273640448


```

**Comment by OverPT** [comment]
Ok, I managed to make it work again. I went to %appdata% and deleted the Spytify entry and now it works. But I'll leave to bug report, so you can check out what might have caused this issue.

**Comment by jwallet** [comment]
Thank you for your well documented report.
That's a tricky one, I'm wondering if nAudio failed (lib to listen to your sound card), did mp3encoder failed or did just spytify failed to update its config values, it would explain why you were not able to repopen it, but it won't explain why it froze itself and also spotify. maybe a combination of all. the only reason that could explain why spotify got frozen, it's nAudio, like your sound card (usb maybe) got unplugged while recording. I will try to find some times to look at it. Thanks again
