### ISSUE TITLE
Disabling Ads Breaks Daily Mix and Spotify Radio

### ISSUE THREAD

**Issue by jwallet** [jwallet/spy-spotify#36]
**What is the bug ?**
> Turning on DISABLE ADS makes the Daily Mix menu to disappear and the radio breaks

**How to reproduce it or what's the expected behavior ?**
> Add a warning before disabling ads that it will break Spotify Radio and Daily Mix

**Comment by stebo02** [comment]
This is because Spytify adds entries to the hosts file. This causes ads, daily mix, radio and friends feed fail to load.

**Comment by jwallet** [comment]
@stebo02  if you want it to work you have to turn off this feature, some Spotify Ads comes from the same IP than the Radio.

**Comment by jwallet** [comment]
already fixed
