### ISSUE TITLE
spotify track id metadata

### ISSUE THREAD

**Issue by alighasemia81** [jwallet/spy-spotify#360]
Hello
First of all, thank you for your efforts
I desperately need a feature.
In the settings, The user can choose which track name to be equal to the track ID in Spotify.
This feature is very helpful.
With this feature, we can get complete track information using Spotify API based on track ID.
I'm looking forward to your answer. thanks.

**Comment by jwallet** [comment]
it's really trivial for spytify to have this feature, but you can fund the issue this way to have a hunter work on it https://github.com/jwallet/spy-spotify#need-a-feature-quicker
