### ISSUE TITLE
.WAV files begin with very noticeable to the ear buggy sound. 

### ISSUE THREAD

**Issue by megalosbasilias** [jwallet/spy-spotify#362]
**What is the bug ?**
> When recording in .wav and playing it back later, the song always begins with an annoying buggy sound, as if it is slowed down or corrupted. Tried it with different players, it's always like this. .mp3 is fine.
> Record in .wav and then play back the recorded track. 

Thanks!

**Comment by jwallet** [comment]
related to #102 ?
