### ISSUE TITLE
Spotify API Access: Spytify sometimes breaks on track change / Not authorized after sometimes

### ISSUE THREAD

**Issue by internetfreak** [jwallet/spy-spotify#370]
**What is the bug ?**
When recording a lot of tracks via the program, it sometimes breaks recording. This can be noticed because the timer within the app doesn't move anymore but Spotify itself just continues playing. It seems that even if this problem happens, the playback data is still recorded but trying to stop Spytify results in force stopping it (clicking Stop again) as it waits for the track to be finished but that never happens.
Afterwards, I often have to delete the resulting file and start over with where I lost connection to record. Also, I then need to create a complete new Spotify App to access API again, otherwise the program will ask for access but doesn't detect anything.

**Track used**
Happens with any track that it currently playing after a longer recording session. The disconnects happen at any time, so I can't give any good time window of how much to record before it starts breaking.

**Screenshots**
Will attach a screenshot if helpful and it happens again.

**Comment by internetfreak** [comment]
I have a screenshot of the problem now that it happened again. This is what I see when it happens:
![image](https://user-images.githubusercontent.com/19251027/126042179-2c7b3324-2b03-43fa-acd2-b81a2138a898.png)

**Comment by internetfreak** [comment]
v1.8 records without any interruptions but I cannot figure out what exactly could've changed between versions which definitely breaks stuff. The only downside is that v1.8 doesn't include any album art or album title and track numbers are missing as well but that can be manually fixed (even with 1.9 I needed to edit tags manually as not everything is being filled)

**Comment by jwallet** [comment]
okay so I may have to upgrade my spotify-net-api to v6

**Comment by jwallet** [comment]
might be related to 
> When using Spotify API, Spytify will now ask the API for current playback status instead of using its own logic

**Comment by jwallet** [comment]
ok it did not crash on my side, I have been recording for more than 10 hours.
![image](https://user-images.githubusercontent.com/23088305/126146826-656eeda6-34f3-43c5-9609-3b3ef8e0b256.png)

I don't know if this can affect the spotify api connection, but my spotify account only serves this spotify app, so if your phone or google home connects to it and you start a new song over there, this might be something I never handled.

to be sure, you may want to create a free spotify account just for recording, connect to the desktop app with this one, and authorize spytify to connect to it, this way no other device will take control of the account. (btw it's still just a guess of what's going on if you are talking about token)

otherwise, the app works with task and threads, I don't know if this can be an issue on a pc with a single core, I only make it work on my 2-3 pc/laptops then I release the new version, so I'm limited on how many hardware (including sound card) that I can test the app on.

**Comment by internetfreak** [comment]
Thanks for trying to fix it, I'll pull the source code later and test if my problem is fixed. The things I noted above were some of my guesses about what could happen, I tried to find out more about it from the source code (I'm a C# dev too) but I wasn't really successfull finding the issue or at least more hints for you what exactly happens.

Since I began to record I only used my account on my PC, I was careful to not use any other device that connects to spotify and possibly breaks my recordings

Tasks/Threads are no problem for my PC, I have a AMD Ryzen 7 3700X so with 8 Cores and 16 Threads there should be enough resources to make sure the recording does get what it wants. I haven't tried another sound device as I only have my onboard sound card otherwise and I am mostly recording while using the PC so the virtual audio cable helps there.
Sleep mode for my PC is disabled, the only thing that would happen is to turn of my displays after some time of being away

**Comment by jwallet** [comment]
i got the same issue today, after recording for 10 hours, still don't know where it comes from, I was not running the app in debug, now I do

**Comment by internetfreak** [comment]
If there's anything I could try, let me know. When I started this issue I also tried to debug a little bit, but I was clueless as well, where to debug to find anything about the issue

**Comment by jwallet** [comment]
I got the issue in debug mode, it looks like the app loose spotify handler process id so it's not bind to it, and a restart is needed

**Comment by jwallet** [comment]
two other exceptions came up, but it comes from spotifyapi.net, and apparently it was fixed in v6, so i will have to upgrade to it

**Comment by jwallet** [comment]
@internetfreak I just released 1.10, you may want to give it a try, I let it run from monday to friday, corrected some issues here and there and it did not got any exception for the last 2 days.

**Comment by internetfreak** [comment]
Thanks for letting me know. Downloaded the new version and started a long enough queue to test it. Will give feedback at a later date

**Comment by internetfreak** [comment]
Encountered another problem. Although recording works fine, the app requested API access again after one hour (when the token is expired and should be renewed). Maybe v6 of the API lib will do that but I wasn't able to grant access (browser starts "loading" indefinitely, the "window can be closed" message never appears). This causes Spytify to fall back to LastFM, effectively getting not all metadata etc.
I have recreated the API application and started recording again so I'll see whether it repeats or not but still noting this here in case it's necessary info

**Comment by internetfreak** [comment]
Okay, it happened again. Because my comment above might be confusing, here's a recap of what happens

**This is what I was doing**
1. Opened Spytify/Spotify
2. Obtained a fresh API app
3. Filled the credentials
4. Started recording

**One hour later, this happens**
1. Spytify switches tracks
2. It notices that the token expired and probably tries to refresh it
3. A sound can be heard, some green stuff flashes briefly before it disappears (I assume it might be an error but it's not possible to read it)
4. A new browser tab opens and I'll get asked to allow access to the developer app again
5. I try to grant access but the browser just loads forever
6. Spytify continues recording and splitting but as it fell back to LastFM, metadata will be missing

Effectively I still have to restart recording after hour but this time due to another error. If you need me to debug something, let me know and I'll try to help as this doesn't seem to happen on your side (yet)

**Comment by jwallet** [comment]
Now I'm wondering if it's an issue with Spotify's recent update, they started to play multiple ads after every song.

**Comment by jwallet** [comment]
what does your api access status is? mine is "granted"
![image](https://user-images.githubusercontent.com/23088305/127161223-edd71816-0360-43d1-9876-2bb71d0109d9.png)

**Comment by internetfreak** [comment]
My api status is development mode which should be normally enough for single user and personal use according to spotify. However I've seen that the app made 26k requests on a single day, this seems quite a lot because I only recorded a few songs (about 2.5 albums)
![image](https://user-images.githubusercontent.com/19251027/127162973-27997b5b-f63b-4469-bd7d-9c38d7ae3e26.png)

Regarding ads, I have spotify premium, so ads shouldn't be an issue for me

**Comment by jwallet** [comment]
![image](https://user-images.githubusercontent.com/23088305/127163287-a4182755-62a9-4674-bd83-0e881bb98efb.png)

**Comment by jwallet** [comment]
did you add your account in the Users and Access section?

**Comment by jwallet** [comment]
>  I've seen that the app made 26k requests on a single day, this seems quite a lot because I only recorded a few songs (about 2.5 albums)

spytify also use the api for track status, maybe I will need to reduce the refresh rate or just use it for metadata. it's indeed to high

**Comment by jwallet** [comment]
I moved some issues to this discussion because they are all related to spotify latest update and spotify dashboard.
- Wrong Redirect URI #376 : probably just did not add `localhost:4002` to their api access app
- Not authorizing correctly #378 & Not working with Spotify Api #377: in developper mode and needs to add his user to the Users list

**Comment by internetfreak** [comment]
Nope, didn't add my own account to that section as this has worked before, so maybe that's the issue for me? But then it should be noticeable quite early instead of after 60 minutes which seems odd.

As for the high request rate, if you run into a rate limit, Spotify will tell you that and let's you know when you can request again. I don't know if that is already handled by the API lib.

**Comment by jwallet** [comment]
I will try to create an app in development this week and try it, maybe in development you are limited to 25k requests or something. I will probably reduce that number quite a lot anyway, like we said, it's too high

**Comment by jwallet** [comment]
also I will look if refresh token is allowed in development

**Comment by internetfreak** [comment]
Spotify itself says this in regards of the developer mode:

> As before, all apps in this mode can access the full breadth of Web API functionality with no additional approvals needed. We designed the development mode to fit the majority of use cases for single-user apps. If you’re exploring the APIs, building home automation, Magic Mirrors or similar use cases, this mode will fit perfectly. If you wish to onboard more than 25 users you will need to submit a quota extension request.

So according to this, refresh tokens etc should work normally. As noted earlier in this issue, 1.8 was able to record for hours (I've recorded 1.5 days worth of music at once) and I did the same with the api app as with 1.9/1.10 (only development mode; no user added to the section; only added ID & Secret to Spytify)

**Comment by jwallet** [comment]
ok so I will remove spotify status from the app to reduce api calls, I think that's the only difference between 1.8 and 1.9

**Comment by internetfreak** [comment]
I have checked out your pull request and started recording again to test it. So far it works without any issue and I'm recording for more than one hour already. I have more songs lined up (at least 5-6h of music, probably more like 10-12h) and will continue recording over night but I don't expect any issues.
Guess it's safe enough for you to merge your changes, release a new version and then this can be closed for good

**Comment by internetfreak** [comment]
Having recorded for almost 48h continously, I can definitely say that the fix works. I have listened to a few recordings across all tracks and I couldn't find anything negative but the plus an metadata automatically fetched for me makes it incredibly easy to extend my library. Thanks for the work, closing this
