### ISSUE TITLE
Spotify API - Invalid request URI

### ISSUE THREAD

**Issue by ChrisFredriksson** [jwallet/spy-spotify#376]
**What is the bug ?**
Starting Spytify, entering Spotify API details, save and press "Start" button. Program opens up browser with link https://accounts.spotify.com/authorize/?client_id=XXX&response_type=code&redirect_uri=http://localhost:4002&state=7b66858a&scope=streaming%20playlist-read-collaborative%20user-read-recently-played%20user-read-playback-state%20user-read-currently-playing&show_dialog=True

Error in the browser from the page opened is;
"**INVALID_CLIENT: Invalid redirect URI**"

![spytify_error](https://user-images.githubusercontent.com/33225247/126890905-609824c2-6ea1-4ad7-b6ad-b17c7e8a17bd.jpg)

**Comment by jwallet** [comment]
did you follow the faq and made sure your port 4002 was whitelisted  https://jwallet.github.io/spy-spotify/faq.html#media-tags-not-found

**Comment by jwallet** [comment]
moving the discussion to #370

**Comment by kekersdev** [comment]
Having the same issue

**Comment by kekersdev** [comment]
Never mind
Tried messing up with `/` after port and it spontaneously started working
