### ISSUE TITLE
Recording is not working with spotify api.

### ISSUE THREAD

**Issue by Spot-nabil** [jwallet/spy-spotify#377]
**What is the bug ?**
I followed steps completely as mentioned.But if i select spotify api it does not record.

**Track used**
> Spotify track/playlist used : https://open.spotify.com/track/2FY7b99s15jUprqC0M5NCT?si=08529316238e4e50

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![Captue](https://user-images.githubusercontent.com/88026890/127120499-b622b899-586b-4ff9-97f3-a38b07e11995.PNG)
![Capture](https://user-images.githubusercontent.com/88026890/127120521-22001dfb-7515-429f-99b8-d41909387234.PNG)

**Comment by jwallet** [comment]
what are your settings on spotify dashboard, did you add `localhost:5000` in the redirect uri list ? are you connected to the same spotify user (desktop) and (dashboard)

**Comment by Spot-nabil** [comment]
> what is the error that you get from spotify api? did you logged in with the same spotify user for the desktop app and in the authorization page ? do you have the same redirect url? I mean in your Spotify dashboard, did you add the "Redirect URI" `http://localhost:5000` in your app setting too ? like this
> 
> ![image](https://camo.githubusercontent.com/fb5b3d88183d98ae5a612ef9406f7c9384fa40c1545a60fd7fc6261636d11bb9/68747470733a2f2f6a77616c6c65742e6769746875622e696f2f7370792d73706f746966792f6173736574732f696d616765732f6661715f73706f746966795f6170695f64617368626f6172642e706e67)

I have added both of them.

**Comment by jwallet** [comment]
ok I just tried you "Api access" and looks like spotify rejected it. Mine is working with the same configs.

your app status needs to be "Granted" 
![image](https://user-images.githubusercontent.com/23088305/127161045-46867190-ac16-41ce-a29e-6af6547711e6.png)

**Comment by jwallet** [comment]
moving the discussion to #370

**Comment by jwallet** [comment]
you have the wrong `client_secret`, I tried your config and got the same error. If I use my own api access and change one char of my client_secret then I also get the same error. In your dashboard, expand/show the client_secret and don't click on `Reset client secret`, copy paste it in Spytify settings.
