### ISSUE TITLE
Spotify API not authorizing correctly

### ISSUE THREAD

**Issue by DJTripleRRR** [jwallet/spy-spotify#378]
![image](https://user-images.githubusercontent.com/50695115/127135617-5f1a4587-d62b-4f76-8f64-bd7f8e5a1e27.png)

I have this issue when trying to connect to Spotify API. When I initially start spying I am able to authorize and it says the window can be closed. It then asks for authorization 5 seconds later and if I click authorize it just does nothing. This error comes up. I am logged into Spotify desktop with my own account and logged into the web browser and authorizing with that same account. I am running the program as administrator and have ensured that port forwarding is on for port selected.

I created the app using my spotify account, put in the key and secret. Everything I have done as instructed but it still comes up with this error. I have also restarted.

It might be worth noting that I created Spotify using my Facebook account. I am unware if that would make any difference.

This is very frustrating. I am using the Last.fm metadata for now.

**Comment by jwallet** [comment]
which track was playing at that moment? this error comes up if spotifyAPI returns an error for the current title?

**Comment by jwallet** [comment]
![image](https://user-images.githubusercontent.com/23088305/127163230-fad9e738-1fda-483b-bfc1-4c666db41281.png)

**Comment by jwallet** [comment]
moving the discussion to #370
