### ISSUE TITLE
Spotify API - excessive API requests

### ISSUE THREAD

**Issue by ChrisFredriksson** [jwallet/spy-spotify#380]
**What is the bug ?**
According to the Spotify Dashboard, I've used up over 23000 requests on the 27/7, and today when I continued to record tracks with Spotify API connected, I get kicked from the Spotify API.

Could it be changed to do a single request per song change/load?

**Screenshots**
![apirequests](https://user-images.githubusercontent.com/33225247/127645531-9c5062b0-7f19-4d72-a6fa-c4dff0d62b9a.jpg)

**Comment by jwallet** [comment]
#370 #379
