### ISSUE TITLE
Only record Spotify Sound

### ISSUE THREAD

**Issue by kekkc** [jwallet/spy-spotify#388]
Hi,

awesome program ;)

Would it be possible to just record the spotify sound? Currently all Windows sound is recorded, which means if I watch a youtube in parallel in Firefox, this will be included in the recorded version.

In windows, I can mute each application individually, so it might be possible to also just record one application. In that case Spytify would be able to run completely in the background.

Greetz

**Comment by jwallet** [comment]
yes see the "how to use it" section here, that links FAQ articles about what you asked
https://jwallet.github.io/spy-spotify/overview.html#how-to-use-it
