### ISSUE TITLE
File Tag Replacing

### ISSUE THREAD

**Issue by GreenDiscord** [jwallet/spy-spotify#391]
Let's say you recorded the song with the basic api, with this feature you can replace the tags from songs already in a library with the spotify api.

This Will Be Helpful for me, others I have no idea we just have to see!

**Comment by jwallet** [comment]
you will have to record again with : 
- Record already recorded tracks instead of skipping them [OFF]
- Re-update already recorded track ID3 tags when they are played [ON]
and have the Spotify API selected
