### ISSUE TITLE
Spytify 1.10.1 always crashes at start

### ISSUE THREAD

**Issue by SamLoomis77** [jwallet/spy-spotify#392]
Since a few days Spytify 1.10.1 (and older) always crashes on start:

# Exception Report

**Version**:     1.10.1.0  
**Region**:        
**Date**: 06.09.2021  
**Time**: 17:26  

**Error Message**: Ausnahme von HRESULT: 0x88890008
 
## Stack Traces
```shell
Top-level Exception
Type:    System.Runtime.InteropServices.COMException
Message: Ausnahme von HRESULT: 0x88890008
Source:  NAudio
Stack Trace: bei NAudio.CoreAudioApi.Interfaces.IMMDevice.Activate(Guid&amp; id, ClsCtx clsCtx, IntPtr activationParams, Object&amp; interfacePointer)
   bei NAudio.CoreAudioApi.MMDevice.GetAudioEndpointVolume()
   bei EspionSpotify.AudioSessions.MainAudioSession.get_AudioDeviceVolume()
   bei EspionSpotify.FrmEspionSpotify.CbAudioDevices_SelectedIndexChanged(Object sender, EventArgs e)
   bei System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   bei MetroFramework.Controls.MetroComboBox.OnSelectedIndexChanged(EventArgs e)
   bei EspionSpotify.Controls.MetroComboBox.OnSelectedIndexChanged(EventArgs e)
   bei System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   bei System.Windows.Forms.ComboBox.RefreshItems()
   bei System.Windows.Forms.ListControl.SetDataConnection(Object newDataSource, BindingMemberInfo newDisplayMember, Boolean force)
   bei System.Windows.Forms.ListControl.set_ValueMember(String value)
   bei EspionSpotify.FrmEspionSpotify.SetAudioEndPointDevicesDropDown()
   bei EspionSpotify.FrmEspionSpotify.Init()
   bei EspionSpotify.FrmEspionSpotify..ctor()
   bei EspionSpotify.Program.Main()
 
```

## Logs
```console


// End
```

## Settings
**advanced_id3_counter_number_as_track_number_enabled**: False 
**settings_media_minimum_recorded_length_in_seconds**: 30 
**settings_media_audio_format**: 0 
**settings_language**: en 
**settings_media_bitrate_quality**: 1 
**app_spotify_api_redirect_url**: http://localhost:4002 
**advanced_record_over_recordings_enabled**: False 
**advanced_file_counter_number_prefix_enabled**: False 
**app_selected_external_api_id**: 0 
**app_last_version_prompt**:  
**advanced_record_everything_and_ads_enabled**: False 
**settings_minimize_to_system_tray_enabled**: True 
**advanced_file_group_media_in_folders_enabled**: False 
**app_selected_audio_device_id**: {0.0.0.00000000}.{ed10b68c-a8e4-4bd2-9ae1-b59fa61e81fd} 
**app_tab_number_selected**: 0 
**settings_output_path**: C:\Users\Admin\Music\Spotify Rec\Donald Fagen\Kamakiriad 
**advanced_file_replace_space_by_underscore_enabled**: False 
**settings_mute_ads_enabled**: True 
**advanced_id3_extra_title_as_subtitle_enabled**: True 
**advanced_record_over_recordings_and_duplicate_enabled**: False 
**advanced_id3_update_recordings_tags_enabled**: False 
**app_analytics_cid**: 092f51be-c79e-40d4-a972-4d2643c6991d 
**app_counter_number_mask**: 000 
**app_spotify_api_client_id**:  
**advanced_watcher_delay_next_recording_until_silent_enabled**: False 
**advanced_record_everything**: False 
**app_spotify_api_client_secret**:  

 
## Assembly References
 - ExceptionReporter.NET, Version=4.0.2.0  
 - MetroFramework, Version=1.4.0.0  
 - mscorlib, Version=4.0.0.0  
 - NAudio, Version=1.10.0.0  
 - NAudio.Lame, Version=1.1.6.0  
 - Newtonsoft.Json, Version=12.0.0.0  
 - PCLWebUtility, Version=1.0.0.0  
 - SpotifyAPI.Web, Version=1.0.0.0  
 - SpotifyAPI.Web.Auth, Version=1.0.0.0  
 - Spytify, Version=1.10.1.0  
 - System, Version=4.0.0.0  
 - System.Configuration, Version=4.0.0.0  
 - System.Core, Version=4.0.0.0  
 - System.Drawing, Version=4.0.0.0  
 - System.IO.Abstractions, Version=13.0.0.0  
 - System.Net.Http, Version=4.2.0.0  
 - System.ValueTuple, Version=4.0.2.0  
 - System.Windows.Forms, Version=4.0.0.0  
 - System.Xml, Version=4.0.0.0  
 - TagLibSharp, Version=2.2.0.0  

## System Info  
```console
Operating System
-Microsoft Windows 10 Pro
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = 120
--FreePhysicalMemory = 10443896
--OSArchitecture = 64-Bit
--OSLanguage = 1031
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.19043

Machine
-BEQUIET-MSI-GTX
--Manufacturer = Micro-Star International Co., Ltd.
--Model = MS-7B17
--TotalPhysicalMemory = 17112076288


```
I cannot get it to work anymore. Anybody got a clue? Cheers.

**Comment by jwallet** [comment]
spytify saves your previous audio device that you used, so I guess the audio device `{0.0.0.00000000}.{ed10b68c-a8e4-4bd2-9ae1-b59fa61e81fd}` got disconnected, maybe an bluetooth audio device. I will fix that and remove the saved audio device if not found, but in the meantime, try to delete all your spytify configs in the repo:    
`%USERPROFILE%\AppData\Local\Spytify\` (paste this line in Windows explorer file path)

**Comment by jwallet** [comment]
reopen if this issue still happens in the latest release
