### ISSUE TITLE
Album art not being saved

### ISSUE THREAD

**Issue by Ali240-max** [jwallet/spy-spotify#393]
In the start, it does save the album art of the first 2 or 3 songs but does not save the album art of the rest.

**Comment by jwallet** [comment]
are you using lastfm.api, because this api is free but not perfect, if you do, you might want to try to connect to the spotify.api like shown here https://jwallet.github.io/spy-spotify/faq.html#media-tags-not-found

**Comment by Ali240-max** [comment]
I figured it out sometime ago. Wasn't filling the album artist space.
