### ISSUE TITLE
Spytify does not detect title changes when spotify is hidden

### ISSUE THREAD

**Issue by supsm** [jwallet/spy-spotify#398]
**What is the bug ?**
> A clear and concise description of what the bug is.

When spotify is minimized to tray, spytify does not detect that the track has changed or an advertisement has started/ended.
> Steps to reproduce the behavior or describe the expected behavior:

Start spying  
Play something  
Minimize spotify to tray  
When the song is finished playing, spytify will not recognize that and will continue recording  

I know this definitely isn't a windows API issue, as hidden windows can still change their title text and other applications can detect it. Currently I'm too lazy to dig into source code, so I will take a bit of a guess. Maybe the HWND can be cached at the start of spying, then it will be used to get the title text. Spotify should not create any new windows, so the HWND will be valid until spotify is closed. I'm think what's currently happening is that all open windows are being checked for the spotify window every time spytify wants to update. If this is the case, caching the HWND will also improve performance and potentially allow spytify to update more frequently.

**Comment by jwallet** [comment]
that's a known limitation, Spotify does not provide changes
