### ISSUE TITLE
Automatically set audio endpoint for spotify process

### ISSUE THREAD

**Issue by pr8x** [jwallet/spy-spotify#401]
Hey, Been using your tool for some time now. It works really well, but there's one thing that is a bit annoying: I have to manually switch the audio endpoint of Spotify every time I want to start a recording session (and switch back when I actually want to listen to music again). This can become quite tedious over time. I experimented a bit and it seems that you can set the audio endpoint of a process with some undocumented (Windows 10+) COM API called `IAudioPolicyConfigFactory` and `SetPersistedDefaultAudioEndpoint`. The [EarTrumpet](https://github.com/File-New-Project/EarTrumpet) project seems to be using exactly that interface. Couldn't quite get it running locally, but I guess with some tinkering it can be done. Before I invest more time in this though: Do you think such a feature makes sense?

**Comment by jwallet** [comment]
it might be related to https://github.com/jwallet/spy-spotify/issues/159

**Comment by jwallet** [comment]
thanks a lot for that link it might help resolve this issue, I did not have enough time to look at it the first time I answered your post. I will look into that.

**Comment by jwallet** [comment]
thanks again, it's now in the master branch
