### ISSUE TITLE
can't record(audio endpoint)

### ISSUE THREAD

**Issue by Maxdontron** [jwallet/spy-spotify#403]
I have followed the guidance of the FAQ and still cannot record
![image](https://user-images.githubusercontent.com/91769391/159123720-1a6f4de8-fe5e-4797-821a-4647f0d14a95.png)
![image](https://user-images.githubusercontent.com/91769391/159123756-a7377af2-00fe-4c5d-ac9a-0f3263720a27.png)

**Comment by Davbra98** [comment]
I just tried with the same configuration as shown in the screenshot and for me it is working. Be aware, that you will not be hearing the music while recording by default but the recording itself will be fine in the end.
If you want to listen to the music while recording consider forwarding the cable to your speakers/headphones as I described in https://github.com/jwallet/spy-spotify/issues/295#issuecomment-752014066

**Comment by Maxdontron** [comment]
,Oh,I've found the problem.Because Spotify was not on the system disk.
