### ISSUE TITLE
The folder setting is being ignored in Windows 10

### ISSUE THREAD

**Issue by robgw** [jwallet/spy-spotify#41]
Changing the Settings > Output path: variable appears to have no effect on where the music is saved. Opening the output path using the browse button within Spytify does open the folder specified in the output path but it is empty. The music is actually being recorded in the default path %HOMEPATH%\music

**How to reproduce it or what's the expected behavior ?**
Change the output path and see where the music is recorded

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by Kloran27** [comment]
Couldn't there (shouldn't there?) be a way to "apply" settings not requiring a restart? I can verify that it is applied after restarting the application however.
