### ISSUE TITLE
Track ID Incomplete

### ISSUE THREAD

**Issue by adamlove86** [jwallet/spy-spotify#419]
Hi jwallet. Spytify is fantastic, I really appreciate the software!
I've noticed that when a track is recorded (I'm using Spotify API), the filename is saved as "Artist Name - Track Name - Extended Remix", however the track ID does not include the "Extended Remix" part. This means that when someone records many versions of a song (or records a particular remix), the track ID won't differentiate between the track and the original. Hopefully a quick & easy fix!
Many thanks for the great work and appreciate your help.

**Comment by jwallet** [comment]
duplicates #417
