### ISSUE TITLE
Split Mode

### ISSUE THREAD

**Issue by DonJema** [jwallet/spy-spotify#423]
Hi, I love Spytify! But often a part of the song start or end is cut off (Crossfade etc. turned off). How about a function Spytify always leaving 5 seconds before and 5 seconds after the end of a track so you can set the start and end point manually with a wave editor...? Or a split-file function that splits the file at the lowest level between two tracks. 
Thanks for your great work!
Cheerz

**Comment by jwallet** [comment]
related to #359
