### ISSUE TITLE
Recording with Spotify API doesn't work anymore.

### ISSUE THREAD

**Issue by Hkllopp** [jwallet/spy-spotify#424]
Hi,

I used to use spytify for months and it worked fine with the spotify API (I created the app and everything) and suddenly stopped working.
To my intuition, the problem is most probably coming with the login in the spotify API, most probbaly because the app cannot read properly the client ID/secret key (no idea why).

**Issue :**
Before the issue happening, when I launched a spytify recording session (with the spotify api), it opened a browser window on the redirection url (usually http://localhost:4002) and asked me for login to spotify. I did and it worked well.
Now, when I start a recording session, no window appears, and even if the client recognize the song playing throught the spotify app (written next to the play icon in the "spy" tab), spytify never launches the recording. The last log is "Debut de l'espionnage"/"Spying started" and nothing happens.

**What I already tried :**
- Recreating an app on the spotify dashboard. Doesn't fix anything.
- Launching by myself the redirecting url on a browser when starting the recording. Interestingly, when I do that, an error message occurs. See screenshots. Obviously, the key (and secret key) is written in the corresponding fields contrary to the error message. I think the error might come from here.
- Creating a recording session with the LastFM API. Working perfectly, as a proof that the error comes with the spotify login.
- Using another song. Doesn't make any difference, as it would be expected because it worked with the LastFM API **AND** the problem occurs event before the recording.

**Case particularity :**
- I'm using the french version of the spytify (and english one of the spotify app)

![image](https://user-images.githubusercontent.com/9498111/168572719-f0245542-26b4-48d8-b6ee-5461a25179f6.png)

**Comment by jwallet** [comment]
can you try the RESET_APP_SETTINGS batch file in the spytify folder

**Comment by Hkllopp** [comment]
Didn't changed anything even by deleting manually the "%userprofile%\AppData\Local\Spytify\*"
The spotify API login page won't open when starting the recording.

**Comment by jwallet** [comment]
I get this error if the [dev app](https://developer.spotify.com/dashboard/applications/) has not the same port than the port provided in Spytify. Otherwise, it works.
It has to be a non-secured address. `http://localhost:5000` not `https://localhost:5000`


![image](https://user-images.githubusercontent.com/23088305/174935054-b7ae967d-b861-4d89-a6ba-efe38daea2cf.png)

**Comment by Hkllopp** [comment]
Unfortunatly, it didn't make any changes.
Both my spotify app and the spytify settings are set to `http://localhost:5000` it still doesn't work.
I don't know if it helps, but when the app worked well (some months ago), when starting the recording, spytify used to open a new tab in my web browser onto the right localhost url. Now, nothing happens when I start a recording, and when I go to the correct localhost port, I still got this error.
Thanks for your help, I hope we'll figure it out !

**Comment by Hkllopp** [comment]
Unfortunately, I had to reinstall windows and now (when changing redirect url to http://localhost:5000), it works again.
Do that's some great news for me but I won't be able to give you further details.
However, I think I wouldn't be able to do it anyway because I provided every details I could in the issue first message.
