### ISSUE TITLE
Add version number to the UI

### ISSUE THREAD

**Issue by rshea0** [jwallet/spy-spotify#426]
Spytify's version number isn't anywhere to be found in the UI.

**Comment by jwallet** [comment]
It can be found in Spytify.exe properties under Details
![image](https://user-images.githubusercontent.com/23088305/174694725-22d9dab4-e411-4d12-ab0c-c535408377d4.png)

Also, if you are not using the latest version, the app will ask you to update, and if you skip it, you will have a reminder at the top-right corner.
