### ISSUE TITLE
Please make MP3 encoder configurable

### ISSUE THREAD

**Issue by MajorP93** [jwallet/spy-spotify#428]
Hi!
Thanks for this awesome piece of software!
Right now I am using .wav as output format and convert it to MP3 manually because I want to use 320kbps CBR for the best possible quality.

It would be awesome if Spytify would offer the option to configure the encoder (variable bit rate / constant bit rate, bit rate 96 - 320).

Thanks!

**Comment by pr8x** [comment]
Yeah, that would definitely be useful. For a simple workaround you can hardcode "320" into `Recorder.cs:261` (instead of `_userSettings.Bitrate`). That will use CBR 320 kbps
