### ISSUE TITLE
Pops and clicks in records

### ISSUE THREAD

**Issue by hulzer** [jwallet/spy-spotify#43]
I tried on two different machines to get a good record result but any mp3 I record does have pops and clicks inside.

I used a premium account at 320 kbps.

![grafik](https://user-images.githubusercontent.com/27423823/44924672-5df11300-ad4c-11e8-87ae-f435b98eab51.png)

Do you have any idea where it comes from?

**Comment by jwallet** [comment]
![image](https://user-images.githubusercontent.com/23088305/44996117-22d12880-af74-11e8-9703-57e914375ca4.png)
not related Spytify, make sure that all other apps are muted before starting a record session, normally Spytify mutes all apps when you click on Start but if you open another app like chrome during the recording session, this one won't be muted, so you might hear sound coming from this app.

clicking and popping sound can be related to you navigating in your folders if System is not muted in the Volume mixer (holds keyboard keys `Windows+R`, then type `sndvol.exe` to open the volume mixer), the popping sound can be related to pop-up windows or ads opening in the background, often opening when visiting streaming or torrents sites without an ad blocker.

**Comment by jwallet** [comment]
I dont know if this can be useful but did you set the bitrate quality to spotify premium in both app, spytify and spotify to record at 320kbps

**Comment by hulzer** [comment]
> but did you set the bitrate quality to spotify premium in both app

No ;-)
This seems to fix the problem.

Thanks.
