### ISSUE TITLE
video ads aren't muted

### ISSUE THREAD

**Issue by Flyingbacen** [jwallet/spy-spotify#434]
**What is the bug ?**
> A clear and concise description of what the bug is.
<b>when you get a video ad on Spotify with the <i>mute ad</i> option enabled, it does not mute the video ad</b>

> Steps to reproduce the behavior or describe the expected behavior: <b>Get an audio ad on Spotify free</b>

**Track used**
> Spotify track/playlist used : <b>Any playlist/track</b>

**Comment by jwallet** [comment]
Video ads are not supported right now, sorry.
