### ISSUE TITLE
Bitrate setting reverting back to 160kbps

### ISSUE THREAD

**Issue by Wink5** [jwallet/spy-spotify#456]
Hi, i have been using spytify for a couple of years now. but with the latest update it is recording at 160kbps. i have spotify premium, set up my api inn spytify and changed the setting for bitrate in spytify but it still records at 160kbps (multiple tracks tested)

when i close the program and reopen it the setting has reverted back to 160kbps, all other setting changes such as audio end point etc have saved without issue

i did notice that there is the option to set the bitrate in the user.config file in app data, i had a look at the file but wasnt 100% how to set the bitrate

any advice gladly received!

**Comment by yvalenty** [comment]
Add this to user.config 
```
<setting name="settings_media_bitrate_quality" serializeAs="String">
    <value>3</value>
</setting>
```

**Comment by Wink5** [comment]
thanks!

**Comment by pdalfarr** [comment]
I think this issue is not fixed. We still need to apply the 'hack' down here in user.config

```
<setting name="settings_media_bitrate_quality" serializeAs="String">
    <value>3</value>
</setting>
```

**Comment by jumph4x** [comment]
I discovered this independently today as well while testing introduction of CBR options.
