### ISSUE TITLE
Recording Bit Rate (Spotify Premium) dropping to default 160k

### ISSUE THREAD

**Issue by martinmain** [jwallet/spy-spotify#470]
I had set the bit rate at 320k in settings, but noted after recording a considerable volume of material the app appears to reset itself to 160k. Is it possible to stop it being reset back to 160k or alternatively showing the rate somewhere on the Spy tab?

**Comment by jwallet** [comment]
Thank you for the report. Good news, it's already fixed. It will be available in the next release. #456
