### ISSUE TITLE
Spotify premium with 'Very High' quality only recording < 180kbps bitrate 

### ISSUE THREAD

**Issue by collinbarlage** [jwallet/spy-spotify#471]
All tracks are only recorded at around 150-170 kbps, when they should be around 300kbps

This happens both on sound device, and virtual cable (also tested on two different Windows computers)

Spotify premium settings:
- Audio quality: Very High
- Auto adjust quality: Off
- Equalizer: Off
- Hardware Acceleration: On

Spytify settings:
- Mp3: 320kbps

**Track used**
An example: https://open.spotify.com/track/2oQVKWHh7FpdPtQkqt3kMc

**Screenshots**
![image](https://user-images.githubusercontent.com/15053712/215021842-707f6e8f-4782-4788-aa89-f77e93673074.png)

**Comment by collinbarlage** [comment]
Looks like this also happens in 1.11, but not 1.10! 
1.10 works fine for me

**Comment by jwallet** [comment]
Thank you for the report. Good news, it's already fixed. It will be available in the next release.

**Comment by firef7y** [comment]
Temporary decision. Add this to program config file:
```
            <setting name="settings_media_bitrate_quality" serializeAs="String">
                <value>3</value>
            </setting>
```
It is located at %userprofile%\AppData\Local\Spytify\
