### ISSUE TITLE
Not Recording in 320 even when selected 

### ISSUE THREAD

**Issue by adamlove86** [jwallet/spy-spotify#472]
File size and bit rate seem a lot smaller - even when selecting 320 from within Spytify
Last 3 tracks in list are for comparison

![image](https://user-images.githubusercontent.com/20361489/215303725-5a6fd9d1-d11e-4fc0-889f-be2aca4a4afc.png)

**Comment by A37stKpDodi4BEr65TXb** [comment]
https://github.com/jwallet/spy-spotify/issues/471

**Comment by firef7y** [comment]
Add this to program config file:
            <setting name="settings_media_bitrate_quality" serializeAs="String">
                <value>3</value>
            </setting>
It is located at %userprofile%\AppData\Local\Spytify\

**Comment by jwallet** [comment]
Thank you for the report. Good news, it's already fixed. It will be available in the next release. https://github.com/jwallet/spy-spotify/issues/456
