### ISSUE TITLE
"Format Not Supported"

### ISSUE THREAD

**Issue by anaanook** [jwallet/spy-spotify#49]
**What is the bug ?**
It says my format is not supported even though it is set to the correct setting

**How to reproduce it or what's the expected behavior ?**
Run the program as normal, click spy, and then you get the error.

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![maya_2018-09-16_13-22-30](https://user-images.githubusercontent.com/8476492/45600575-c0384d80-b9b3-11e8-9cd1-7956c564052f.png)

**Comment by jwallet** [comment]
did you changed the output folder path, looks like this message will show up if Spytify has no access to the directory. like outputting files in C:\Windows\ in my case ?

**Comment by anaanook** [comment]
None of these things had any effect, in fact I was already running as admin when I hit the bug.  The workaround I figured out is using the 'hdmi audio' output from my monitor, which goes through my nvidia GPU.  this worked but is annoying because I cant run through my headphones easily.   There's clearly some issue with the driver/how the driver is reporting the format.

**Comment by jwallet** [comment]
try to lower the quality a bit.
also i made changes to the app, next build it will tell you what the actual issue is, it will output the recorder exception. but, i'm pretty sure it will still be about the quality the format

**Comment by jwallet** [comment]
issue might be related to #54
