### ISSUE TITLE
Some beats are missing in the beggining of the tracks

### ISSUE THREAD

**Issue by edil-it-them** [jwallet/spy-spotify#490]
1. Reckord track
**Track used**
Any track but for example sake https://open.spotify.com/track/2BH9ryNKlONkENIhgMM4lq

I can hear the jumping beat in the first ~5 secs and see that the recording is 5 seconds less than the original audio on Spotify.
<img width="508" alt="image" src="https://user-images.githubusercontent.com/44370635/225914143-7bec4f72-792e-41d7-9380-6ab48546b035.png">
<img width="740" alt="image" src="https://user-images.githubusercontent.com/44370635/225914293-74d1bc27-ce48-4eed-8a76-12b29eb41915.png">

**Comment by jwallet** [comment]
duplicates #359
