### ISSUE TITLE
 start from Spytify-v1.11 version , App  doesn't recognize Premium account and forces it to record at 160kbps instead of 320kbps.

### ISSUE THREAD

**Issue by EliOleg** [jwallet/spy-spotify#491]
Spytify doesn't recognize Premium account and forces it to record at 160kbps instead of 320kbps.

I using - windows 10 Home, please see on Screenshots..

**Track used** - any tracks

![Capture](https://user-images.githubusercontent.com/129700700/229389887-36def97b-e352-4d10-a348-3338058f73d6.PNG)

-----------------------------------------------------------

some additional information that i found while checking the last couple of releases..

starting from the version Spytify-v1.11 the problem occurs, 

before that version Spytify-v1.10.1 and below everything works well

Many Thanks,
Eli

**Comment by jwallet** [comment]
Thank you for the report. Good news, it's already fixed. It will be available in the next release. https://github.com/jwallet/spy-spotify/issues/456
