### ISSUE TITLE
Recording only in 160kbps mode

### ISSUE THREAD

**Issue by M4st3rITA** [jwallet/spy-spotify#492]
Hello everyone!

After a while I started using Spytify again and realised that although I set Spotify to 'play in high quality' and did the same in Spytify, the MP3s are actually all at about 160kbps.

How can I solve this?
<img width="475" alt="Screenshot 2023-04-06 alle 12 58 03" src="https://user-images.githubusercontent.com/53777627/230357794-c95b1031-e2be-428e-82d8-dd49623a2a41.png">
<img width="1294" alt="Screenshot 2023-04-06 alle 12 57 34" src="https://user-images.githubusercontent.com/53777627/230357796-af36e9f0-f75f-4f1c-879a-352e1d57620a.png">
<img width="1073" alt="Screenshot 2023-04-06 alle 12 57 18" src="https://user-images.githubusercontent.com/53777627/230357799-8b56c82f-3758-414d-bc01-5fed5811a5a2.png">

My installation is on a correctly running and up-to-date Windows11 virtual machine.

The tracks recorded about 1 year ago were correctly exported in 320kbps.

I have tried several tracks (all recent) and the problem still persists.

**Comment by M4st3rITA** [comment]
I have already done the following tests
- tried installing Spotify and Spytify in a VM (this time of Windows10) created specifically for the purpose, the problem persists
- tried using an older version of the Spotify client (1-1-84-716 from about 1 year ago) and the problem persists
- tried using an older version of Spytify and the problem persists
- tried installing Spotify and Spytify on a different computer (where there was no record of installation of either software) and the problem persists
- tried installing different software (like Sidify) and MP3s are created-exported correctly in 320kbps

**Comment by jwallet** [comment]
Thank you for the report. Good news, it's already fixed. It will be available in the next release. https://github.com/jwallet/spy-spotify/issues/456
