### ISSUE TITLE
Error while recording (when trying to use mp3)

### ISSUE THREAD

**Issue by WillCritForFood** [jwallet/spy-spotify#54]
When trying to record under the mp3 option I am getting the error, 
**"Error while recording: Unknown exception: $Unsupported number of channels 8
Parameter name: format"**

This happens only if the mode is set to mp3 (not wav) and I have tried adjusting other settings (such as bitrate and output path) but no success.

![image](https://user-images.githubusercontent.com/43742539/46278029-056f8a00-c533-11e8-8283-96d1f5ba1cca.png)

**Comment by jwallet** [comment]
ok i will look at this if it can support all channels, try to set it to only 2 channels. probably you can set it in your sound software like RealTek

**Comment by jwallet** [comment]
not supported by the library used naudio-lame, so you will have to dowgrade will recording (to stereo, like headphones)

**Comment by WillCritForFood** [comment]
how do you downgrade recording? I am currently using default settings for my sound driver (realtek).

**Comment by jwallet** [comment]
no idea, you will have to google your sound card, my guess is that your realtek software is set to something like 7.1 surround and you need to set it to speakers or headphones to go back to two channels. even fake surround sound like sound card software does, can messed up with spytify, if you have real 7.1 just unplug all colored wires behind your pc that goes to your sound card except the green one.
