### ISSUE TITLE
debug windows 7

### ISSUE THREAD

**Issue by jwallet** [jwallet/spy-spotify#57]
[Debug.zip](https://github.com/jwallet/spy-spotify/files/2475637/Debug.zip)

**Comment by 1242637** [comment]
[Temp.zip](https://github.com/jwallet/spy-spotify/files/2475658/Temp.zip)

**Comment by jwallet** [comment]
[Release.zip](https://github.com/jwallet/spy-spotify/files/2475669/Release.zip)

**Comment by jwallet** [comment]
1.1.3.1
