### ISSUE TITLE
Song Title instead of Album name

### ISSUE THREAD

**Issue by Thari0** [jwallet/spy-spotify#59]
**What is the bug ?**

In meta data in place of Album name there is a song name, so its hard to organize it properly later.

![przechwytywanie](https://user-images.githubusercontent.com/38658176/47083663-9b810100-d211-11e8-969b-f37b9f0dd41f.PNG)

**Comment by jwallet** [comment]
The api grabs the single instead of the real one, so that's why we get that error. This will probably get fixed only if I use another api

http://ws.audioscrobbler.com/2.0/?method=track.getInfo&api_key=c117eb33c9d44d34734dfdcafa7a162d&artist=System%20Of%20A%20Down&track=Chop%20Suey

**Comment by jwallet** [comment]
you can now try the newest release [1.2.0](https://github.com/jwallet/spy-spotify/releases/tag/1.2.0) and follow the instruction in `Spytify.exe.config` file that comes with Spytify
