### ISSUE TITLE
Version 1.1.3.1 crashes on Win 10 Pro x64

### ISSUE THREAD

**Issue by tom08zehn** [jwallet/spy-spotify#60]
Using Spytify v1.1.3.1 under Windows 10 Pro x64 1709 (Build 16299.125). Version 1.1.0.1 crashed after 1 or 2 songs. Version 1.1.3.1 now crashes after 1-5 songs. So the new version is a bit better but not crash-proof. Any ideas? Maybe you can improve some stuff like you already did for Win7? The program crashes immediately so I even cannot create a crash dump report for you using Windows Task Manager. I recognized that while recording the HDD load is almost 99-100%.

**Comment by jwallet** [comment]
the hdd load should not be that high, should be around 10%

**Comment by tom08zehn** [comment]
This seems to be a general issue in Win 8.1 and 10. You can read about this
in many user forums. But maybe this causes Spytify to crash because it
cannot swap to disk.

jwallet <notifications@github.com> schrieb am Do., 18. Okt. 2018, 17:29:

**Comment by jwallet** [comment]
after 20 songs recorded still nothing, maybe you have an hardware issue : 
![image](https://user-images.githubusercontent.com/23088305/47195291-3f110500-d329-11e8-90f7-7c2901c4ea7a.png)

**Comment by tom08zehn** [comment]
I followed some online tips on how to decrease HDD load for Win 10 (disable
indexing for all hard drives, disable Application Experience
'compattelrunner.exe' tasks in Windows' Task Planer etc.) and after that I
could record for multiple hours without crash 👍🏻

jwallet <notifications@github.com> schrieb am Fr., 19. Okt. 2018, 04:58:

**Comment by jwallet** [comment]
I will close this issue then, if someone has more details and thinks it comes from spytify, just reopen the issue
