### ISSUE TITLE
change input device

### ISSUE THREAD

**Issue by Jocky92** [jwallet/spy-spotify#61]
this tool is really nice and i like to use it so often :) 
I have connected some audiocards to my computer with advanced configuration. my Spotify do not use the default audio output device and when i now try to use spytify i can not connect to spotify and cannot record songs. 

i would like to see an configuration where i can change the audio input device in spytify. So spytify records just the sound from this device and not only my standard windows sound. This would be really nice because sometimes i recorded songs and got some windows sounds in the songs too ;)

or maybe i do not see the configuration. is it already possible to change the input device?

**Comment by jwallet** [comment]
![image](https://user-images.githubusercontent.com/23088305/50881537-edb86500-13af-11e9-8a70-d28ecc7ad7f6.png)
