### ISSUE TITLE
Album Art not always showing; Album info are wrong

### ISSUE THREAD

**Issue by WillCritForFood** [jwallet/spy-spotify#62]
I'm not sure if this is a known bug but sometimes album art isn't added for some songs.

**Comment by jwallet** [comment]
this is a known issue, but since i used a third party api to get album info, it is possible that it can't get all songs right. so i can't fix this at the moment, maybe if one day i find a better api or spotify lets anonymous user use their api.

**Comment by jwallet** [comment]
you can now try the newest release [1.2.0](https://github.com/jwallet/spy-spotify/releases/tag/1.2.0) and follow the instruction in `Spytify.exe.config` file that comes with Spytify
