### ISSUE TITLE
timer for recording 

### ISSUE THREAD

**Issue by skyerjoe** [jwallet/spy-spotify#63]
An timer for recording will be great 

regards john

**Comment by Joeasaurus** [comment]
Maybe an option to stop after X songs as well, instead of waiting for me to stop playing music.

**Comment by jwallet** [comment]
there is no control alike google timer available, so i guess it will be a set of all these values
- [ ] hours (for an album)
- [ ] minutes (for a set of songs)
- [ ] seconds (for ringtones)

**Comment by jwallet** [comment]
![image](https://user-images.githubusercontent.com/23088305/50881357-56eba880-13af-11e9-8735-682ace964b38.png)
