### ISSUE TITLE
Multi channel error

### ISSUE THREAD

**Issue by yuukiw** [jwallet/spy-spotify#65]
i always get 
// Error while recording: Recording multi-channel files is not supported, reduce the number of channels to 2 (stereo) or 1 (mono).

i use the default stereos settings through, no enable virtual suround sound or anything like this

**Comment by jwallet** [comment]
![image](https://user-images.githubusercontent.com/23088305/49913050-1ead8480-fe5a-11e8-8dc9-d16a11ad5301.png)

**Comment by jwallet** [comment]
i will close it, but feel free to reopen if my answer does not resolve your issue

**Comment by fpt** [comment]
I got the same error as yuukiw wrote.
My RealTek audio has stereo setting but it didn't change the situation :(

So I plugged in an USB audio and the error was gone.
Thank you for creating nice tool! 😄

**Comment by akhilyeddula** [comment]
I know this is closed, but I just wanted to put this out there in case someone else had a similar issue. For me, it was SoundSwitch that caused the issue for me. Check if you have any sound related applications running in the try or the background.
