### ISSUE TITLE
Songs are identified as Ads

### ISSUE THREAD

**Issue by FreedomPrevails** [jwallet/spy-spotify#66]
**What is the bug ?**
A song is identified as an Ad.

**How to reproduce it or what's the expected behavior ?**
Play the song, it shows it is an Ad, while it is not.

**More info**
If I switch to another song and then play back the same song again. it starts to record it.

**Comment by jwallet** [comment]
![image](https://user-images.githubusercontent.com/23088305/49416532-3db86200-f748-11e8-8192-c271b242ddc8.png)
