### ISSUE TITLE
Stop recording on track end

### ISSUE THREAD

**Issue by MCOfficer** [jwallet/spy-spotify#74]
**What problem will this new feature resolve ?**
> When recording long playlists and stopping in the middle, i have to perfectly stop playback at the end of a track, otherwise i end up with an incomplete recording. There are ways to work around it, but it's tedious.

**What feature or enhancement would you like to see added ?**
> A Button (or maybe checkbox) that makes the recording stop after the next track has ended. This way i can just press the button, wait a bit and everything is fine.

**Comment by jwallet** [comment]
I cannot believe I did not think about that haha
