### ISSUE TITLE
Stackoverflow

### ISSUE THREAD

**Issue by eleasarchriso** [jwallet/spy-spotify#82]
**What is the bug ?**
A stackoverflow exception is happening.

**How to reproduce it or what's the expected behavior ?**
* Have the latest spy spotify
* use this playlist: https://open.spotify.com/user/ankeschimanski/playlist/4kUvUzYz5XnMm2eLHeB1JX?si=B8G93VG3TXyc4zGSsI6nlg
* start recording

**Code**

The line `MapLastFMTrackToTrack(retryWithTrack, trackExtra);` goes into an endless loop and causes a stackoverflow exception. Class `LastFMAPI` line 64.

(And thanks for including the code to use the Spotify API - super helpful now!)

**Comment by ulair** [comment]
This might be related: Before it eventually crashes it also constantly sends repeating requests for track info to last.fm (~6 per second on my machine).
