### ISSUE TITLE
Alternative track splitting method

### ISSUE THREAD

**Issue by Jacajack** [jwallet/spy-spotify#83]
First of all, thank you for your time and effort put into development of SpySpotify - it's really great.

**What problem will this new feature resolves ?**
I believe I came up with a solution to overlapping/missing track segments problem. This leads to two different issues:
 - In many cases you miss the first note of a song. 
 - It is impossible to perfectly split the tracks in Audacity.

**What feature or enhancement would you like to see added ?**
From looking at the code, I deduced that a new recording is started when SpySpotify receives an information about track change.

What I'd like to propose is a different method of handling the captured audio data. Suppose you have a ring buffer into which the incoming stream is constantly written. Now, when a track change is detected, a snapshot of the write pointer is taken. You now know that all the data up to that pointer belongs to the previous track and everything that comes after it is the new track. This approach completely eliminates overlapping data problem and leaves place for some calibration. 

Since the track change notification is surely delayed a bit, the stored write pointer will be delayed itself. Nothing, however, stops you from shifting it by some calibration value (either somehow calculated by SpySpotify or entered by the user) and taking that as the real track change point. This idea is very similar to pre-triggering you might find in digital oscilloscopes (https://www.tiepie.com/en/fut/pre-trigger).

Maybe this lovely illustration helps you to understand better what I mean:
```
--------------------------------------------------- - - -
  Old track      |     ???     |   New track 
--------------------------------------------------- - - -
                    ^                  ^         ^
                    C    Calibration   S         W
                    |  <-------------  |                    
                                              
W - current write pointer
S - stored pointer (when notification was received)
C - actual track change point   
                                                 
```

Additionally, the lack of overlapping audio data allows you to simply stack the tracks in Audacity and safely merge them into an entire album. Splitting tracks by hand is also easier if you're guaranteed that nothing is repeating. 

Unfortunately, I don't know C#, so I can't really help you with the implementation. I just wanted to put forward my idea and hear your opinion.

Thanks for your consideration in advance.

**Comment by jwallet** [comment]
this is actually what happens. Spotify title is not accurate
```
------------- Spotify Window - Audio ---------------
  Old track            | ? ? ?  | New track
------------- Spotify Window - Title ---------------
  Old track       |  ? ? ? |    New track 
----------------------------------------------------
                  ^    ^   ^   ^
                  S    D   W  WDD

W - current write pointer
WDD - current write pointer if delay was detected
S - stored pointer (when notification was received)
D - delaying new track record for a max of 2 seconds if sounds is still detecting         
                                              
```

**Comment by jwallet** [comment]
try to make a playlist first, Spotify has difficulity to set its title properly when switching between playlist/radio/artist or searching... so about everything except playing a whole album or a whole playlist. So get all your songs into a custom playlist, then record that and disable Ads using the Spytify setting
