### ISSUE TITLE
Capture artist info

### ISSUE THREAD

**Issue by plsloan** [jwallet/spy-spotify#84]
**What is the bug ?**
> A clear and concise description of what the bug is.

It looks like it is not capturing the artist info currently. Even just capturing the primary artist would be useful since I sync my music to Google Music.

**How to reproduce it or what's the expected behavior ?**
> Steps to reproduce the behavior or describe the expected behavior:

You can see this using the screenshot that I provided.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![Capture](https://user-images.githubusercontent.com/25558732/54530308-cbffcf00-4958-11e9-8497-04138d61c5d3.PNG)

**Comment by jwallet** [comment]
could you add the link to the spotify song

**Comment by plsloan** [comment]
This was the case for every song.
