### ISSUE TITLE
1.2 Next Track Detection

### ISSUE THREAD

**Issue by jumph4x** [jwallet/spy-spotify#85]
Upgraded to v1.2 and it has a tough time capturing when Spotify starts playing and when Spotify transitions to next track. 

This might manifest itself as:
- starting to spy but not beginning to record
- starting to record but not stopping and restarting on track transition

This affects v1.2 release within the week, downgrading to v1.1.4 fixes the issue. To reproduce, simply try to record a playlist of 3 tracks on latest version of everything, Windows 10. I am using a USB soundcard, Focusrite Scarlett 2i2.

Thank you for this time on this project <3.
Sending love from Oakland.

**Comment by jwallet** [comment]
if you are experimenting overlapping tracks, try to disable `delay next recording if sound is detected`. sometimes spotify switch to a new track title even if the current track is still playing, but this can affects tracks that are always delivering sounds between tracks, like audio books. the current delay setting is not more than 2 seconds btw.

**Comment by jumph4x** [comment]
That is not what I'm experiencing.
