### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by FrezixAlan** [jwallet/spy-spotify#86]
**What is the bug ?**
> A clear and concise description of what the bug is.
The application closes roughly 1 hour while running midway while song plays. Is there a way to check for error logs? 
**How to reproduce it or what's the expected behavior ?**
> Steps to reproduce the behavior or describe the expected behavior:
Unknown. Tried on windows 10, 7. All requirements met. 
**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by FrezixAlan** [comment]
In windows 7. It will just not respond* 
In win 10. Window just closes without notifications

**Comment by FrezixAlan** [comment]
Btw it also doesnt update the file names stright away? 

http://imgur.com/lxpnI0J

**Comment by jwallet** [comment]
thanks related #82
