### ISSUE TITLE
Only 3.5 mm jack conneced devices work for recording

### ISSUE THREAD

**Issue by Pak9999** [jwallet/spy-spotify#89]
**What is the bug ?**
None of my USB headsets work for recording. I have tried it with the G35 and G633. But all of my 3.5mm headphones do work.  With the USB ones i can hear the music but spytify does recognize any music being played in Spotify. 

**How to reproduce it or what's the expected behavior ?**
Try recording running a recording with an USB headset.   

**Screenshots**
None

**Comment by jwallet** [comment]
make sure Spotify and Spytify are set correctly

![test2](https://user-images.githubusercontent.com/23088305/57564449-b798eb00-7379-11e9-982e-bd75ad13d6fc.gif)

**Comment by Pak9999** [comment]
Thank you for the quick response. You help got me further. It detects the song now. But now i get the this error: 
[12:13:25] // Spying
[12:13:29] // Error while recording: Recording multi-channel files is not supported (8 channels), reduce the number of channels to 2 (stereo) or 1 (mono).

**Comment by jwallet** [comment]
some people reported that their sound card is not supported, but i can do much about it, like in this issue #65, you can also try the steps that I'm showing to set your sound card to stereo (second reason of having this error message) goo luck

**Comment by Pak9999** [comment]
![Snag_15cee60b](https://user-images.githubusercontent.com/32219536/57568952-9c1bf780-73ee-11e9-86d5-6302eff56af7.png)

**Comment by jwallet** [comment]
You can use the first method here, to set Spotify on a different sound card, like your `AMD HD Audio` or `Realtek audio`

**Comment by Pak9999** [comment]
Ok thank you for the help. I have solved it now. I had to put both outputs on the G633

![Snag_15d87ca2](https://user-images.githubusercontent.com/32219536/57569051-126d2980-73f0-11e9-8cde-6f174deecc5b.png)
