### ISSUE TITLE
The recorded track is shorter than the original and/or having missing beats (faster than the original)

### ISSUE THREAD

**Issue by robert712002** [jwallet/spy-spotify#92]
**What is the bug ?**
> Sometimes, somewhere in the track, there is few milliseconds missing or skipping

**How to reproduce it or what's the expected behavior ?**
> Just run the Spytify

**Comment by jwallet** [comment]
if you mean it misses a bit of the beginning or the ending, it's sadly... normal, spotify does not always provide the right info at the right time, resulting with a delay at the start or the end.

**Comment by robert712002** [comment]
No, it's not that. I get a perfect start and end but in the middle, it can sometimes skip a beat. 

Also not related, album art isn't getting downloaded, at all

**Comment by jwallet** [comment]
does the in-app f.a.q helps?
> Background noise/sound was recorded on the saved track file [Second case]

**Comment by robert712002** [comment]
Sorry for not replying, totally forgot to.
No I've tried muting everything manually, left the PC and it still did that

**Comment by jwallet** [comment]
sorry, i forgot to come back here, but by any chance, do you still have the recorded file that you can probably upload right here in this reply box, and the song on spotify
https://open.spotify.com/browse/featured

**Comment by robert712002** [comment]
Here's one instance of it happening:
https://open.spotify.com/album/1V6fHc3rVOVvZqOgEkJCxT?si=6p6vqBdISMeU1bEeda1VqQ

[Gopnik McBlyat - Supreme Memebass Gavno.zip](https://github.com/jwallet/spy-spotify/files/3256361/Gopnik.McBlyat.-.Supreme.Memebass.Gavno.zip)

As you can see its 10 seconds shorter than on Spotify. Also, it didn't download the album art but you know about that issue already

**Comment by jwallet** [comment]
sorry for the delay, summer time.
i tried to record the song you were trying and got a perfect result. then, i compared yours to mine with audacity and like you said it skips some beats and end with a song 10 secs shorter. My guess is that your pc is not listening fast enough to the wav stream, so the writer misses some beats. like I said my guess is still cpu related, so if Spytify FAQ - Background noise - Second case - does not apply to you and you had your cpu in full capacity (no save mode) then try a different PC. You need something that does not go in saver mode (Power plan)

**Comment by jwallet** [comment]
I tried different settings to find the issue;
What I found using one computer is that in Power Saving Plan the recording gets shorter than the original. The .wav was recording fine, only the .mp3 had issue. So the issue comes from the third party package libmp3lame.
I will have a better look at the mp3 writer while the power saving mode is enabled
