### ISSUE TITLE
PodCasts are not recogniced

### ISSUE THREAD

**Issue by FestFlauschig** [jwallet/spy-spotify#94]
First of all, thank you for the great tool. It works fine with music and audio books.
But whenever I start recording podcasts, it doesn't start recording.

I know, it was mentioned here:
https://github.com/jwallet/spy-spotify/issues/66

But there can you provide a solution? I use Spotify Premium, so I actually don't need the "remove/mute ads" option.

**Comment by jwallet** [comment]
does this option works for you
![image](https://user-images.githubusercontent.com/23088305/57590667-5e58c500-74fb-11e9-92af-c74789e067b4.png)

**Comment by jwallet** [comment]
it's been a long time since last post, feel free to reopen with more detail
