### ISSUE TITLE
All songs are about 2 BPM faster than they should be, makes them all sound slightly weird.

### ISSUE THREAD

**Issue by TXby0417** [jwallet/spy-spotify#96]
Songs recorded using Spytify are typically 2 BPM faster than they should be. Not sure if this is a Spotify thing, my soundcard, or just some weird occurrence. Trying to figure this out soon because I have a DJ gig coming up and Spytify is the by far the best way to obtain music and tags effortlessly.

Edit: I played the spotify version of a couple songs, against songs that I already had in my library, and they were the same speed. I will attempt to record again using a different soundcard and see if there is any difference.

**Comment by jwallet** [comment]
is it #92 related?

**Comment by TXby0417** [comment]
Not related. The whole song is there, when it gets analyzed by the DJ software/played against an officially downloaded version it is just faster than the official one. Every song(close to 1300) were like that. 

Also when I went to use other soundcard, I wasn't able to because there's no support for more than two channel recording?

**Comment by jwallet** [comment]
an official downloaded version will always be a better quality than one that got recorded from a wav and transcode to mp3 stereo. wav have some limitations. but i will defenitively look at it and see if there is any other reason that the recorded file will play faster than the original one

> last comment related to #97

**Comment by TXby0417** [comment]
Not sure why I put official, they're just SoundCloud downloads, but the rip quality should be as good as your soundcard/stream. I have ripped from Spotify before using audacity and the quality is excellent, but that takes forever to do it that way since you have to type everything in manually and wait for it to encode as mp3 then start the stream for the next song. When I get home tonight I'll see about uploading a song I already had and one the was ripped using the spy so you can hear what I'm talking about

**Comment by TXby0417** [comment]
[Songs.zip](https://github.com/jwallet/spy-spotify/files/3259126/Songs.zip)
Here is a sample. I even included a version that was just ripped from spotify today using audacity.

**Comment by jwallet** [comment]
the length might be the same spytify/audacity, but there is nothing at the end of the recorded song with spytify.
i'm pretty sure this is #92 related

**Comment by jwallet** [comment]
you might want to check #103 to install a better driver for spytify.
