### ISSUE TITLE
NAudio Multi channel pass through

### ISSUE THREAD

**Issue by Pak9999** [jwallet/spy-spotify#97]
**What problem will this new feature resolves ?**
> As my headset only has an 7.1 surround mode. I'm unable to use it with the program. Changing over everything to headphones is a real hassle if i want to record a quick thing.

**What feature or enhancement would you like to see added ?**
> It can still record in stereo but it could let you use more then stereo sound. 

![Snag_55dd1ff](https://user-images.githubusercontent.com/32219536/58438414-0b703780-80cf-11e9-8f33-66ee5aade6f7.png)
![Snag_55dec8c](https://user-images.githubusercontent.com/32219536/58438418-0f03be80-80cf-11e9-9681-63d8caddc1e4.png)

---
Want to back this issue? **[Post a bounty on it!](https://issuehunt.io/r/jwallet/spy-spotify/issues/97)** We accept bounties via [IssueHunt](https://issuehunt.io/r/jwallet/spy-spotify).

**Comment by jwallet** [comment]
nAudio library does not seem to be able to record in stereo when your sound card is set to 7.1 surround, because it uses the device, it does not control your sound card.
many computers have more that one sound device, you could use another one instead

![image](https://user-images.githubusercontent.com/23088305/57564449-b798eb00-7379-11e9-982e-bd75ad13d6fc.gif)

**Comment by Pak9999** [comment]
Yeah i know i can swap the audio devices. But i would like a feature were you can use 2 audio outputs, one for recording and the other one for listening.

**Comment by jwallet** [comment]
opened a pr that get left/right channels on a multi-channel and encode to stereo. if the quality is less I suggest installing Virtual Cable Driver available in Settings and use it to isolate both apps Spotify and Spytify in their own audio device. It won't record external sound. Configure VB-Cable to be on 2 channels and format 24bits, 48000hz
